// Auto-generated from DLD Building/Unit Registration data (3,197 records, Q1 2026)
// Generated by scripts/processBuildingData.py
// DO NOT EDIT MANUALLY

export interface ProjectUnitDetail {
  name: string;
  areaDld: string;
  areaPcis: string;
  totalUnits: number;
  roomMix: Record<string, number>;
  primaryType: string;
  offplanUnits: number;
  readyUnits: number;
  offplanPct: number;
  freeholdPct: number;
  avgBuiltUpArea: number;
  parkingRatio: number;
  registrationDate: string;
}

export interface AreaBuildingStats {
  totalRegistered: number;
  offplanUnits: number;
  readyUnits: number;
  offplanPct: number;
  roomMix: Record<string, number>;
  primaryType: string;
  avgBuiltUpArea: number;
  parkingRatio: number;
  projectCount: number;
  projects: string[];
}

export interface MarketBuildingStats {
  totalRegistrations: number;
  offplanRegistrations: number;
  readyRegistrations: number;
  offplanPct: number;
  uniqueProjects: number;
  uniqueAreas: number;
  avgBuiltUpArea: number;
  topRoomType: string;
  dataDate: string;
}

export const REAL_PROJECT_UNITS: ProjectUnitDetail[] = [
  {
    "name": "DAMAC ISLANDS 2 - ANTIGUA 1",
    "areaDld": "Al Yelayiss 1",
    "areaPcis": "SILICON OASIS",
    "totalUnits": 468,
    "roomMix": {
      "4BR": 236,
      "5BR": 232
    },
    "primaryType": "Villa",
    "offplanUnits": 468,
    "readyUnits": 0,
    "offplanPct": 100.0,
    "freeholdPct": 100.0,
    "avgBuiltUpArea": 251.7,
    "parkingRatio": 2.0,
    "registrationDate": "2026-01-29"
  },
  {
    "name": "Verdana 4",
    "areaDld": "Dubai Investment Park First",
    "areaPcis": "Dubai Investment Park First",
    "totalUnits": 306,
    "roomMix": {
      "2BR": 101,
      "3BR": 42,
      "4BR": 163
    },
    "primaryType": "Villa",
    "offplanUnits": 306,
    "readyUnits": 0,
    "offplanPct": 100.0,
    "freeholdPct": 100.0,
    "avgBuiltUpArea": 208.7,
    "parkingRatio": 1.0,
    "registrationDate": "2026-01-07"
  },
  {
    "name": "Verdana 7",
    "areaDld": "Dubai Investment Park First",
    "areaPcis": "Dubai Investment Park First",
    "totalUnits": 293,
    "roomMix": {
      "2BR": 88,
      "3BR": 58,
      "4BR": 147
    },
    "primaryType": "Villa",
    "offplanUnits": 293,
    "readyUnits": 0,
    "offplanPct": 100.0,
    "freeholdPct": 100.0,
    "avgBuiltUpArea": 204.6,
    "parkingRatio": 1.0,
    "registrationDate": "2026-01-07"
  },
  {
    "name": "Verdana 6",
    "areaDld": "Dubai Investment Park First",
    "areaPcis": "Dubai Investment Park First",
    "totalUnits": 280,
    "roomMix": {
      "2BR": 110,
      "3BR": 32,
      "4BR": 138
    },
    "primaryType": "Villa",
    "offplanUnits": 280,
    "readyUnits": 0,
    "offplanPct": 100.0,
    "freeholdPct": 100.0,
    "avgBuiltUpArea": 201.2,
    "parkingRatio": 1.0,
    "registrationDate": "2026-01-07"
  },
  {
    "name": "Verdana 5",
    "areaDld": "Dubai Investment Park First",
    "areaPcis": "Dubai Investment Park First",
    "totalUnits": 271,
    "roomMix": {
      "2BR": 74,
      "3BR": 47,
      "4BR": 150
    },
    "primaryType": "Villa",
    "offplanUnits": 271,
    "readyUnits": 0,
    "offplanPct": 100.0,
    "freeholdPct": 100.0,
    "avgBuiltUpArea": 210.9,
    "parkingRatio": 1.0,
    "registrationDate": "2026-01-05"
  },
  {
    "name": "The Valley - Alva",
    "areaDld": "Al Yufrah 1",
    "areaPcis": "AL FURJAN",
    "totalUnits": 196,
    "roomMix": {
      "3BR": 98,
      "4BR": 98
    },
    "primaryType": "Villa",
    "offplanUnits": 196,
    "readyUnits": 0,
    "offplanPct": 100.0,
    "freeholdPct": 100.0,
    "avgBuiltUpArea": 272.6,
    "parkingRatio": 2.0,
    "registrationDate": "2026-01-29"
  },
  {
    "name": "The Valley - Alva 2",
    "areaDld": "Al Yufrah 1",
    "areaPcis": "AL FURJAN",
    "totalUnits": 176,
    "roomMix": {
      "3BR": 88,
      "4BR": 88
    },
    "primaryType": "Villa",
    "offplanUnits": 176,
    "readyUnits": 0,
    "offplanPct": 100.0,
    "freeholdPct": 100.0,
    "avgBuiltUpArea": 271.6,
    "parkingRatio": 2.0,
    "registrationDate": "2026-01-29"
  },
  {
    "name": "The Valley - Alva 3",
    "areaDld": "Al Yufrah 1",
    "areaPcis": "AL FURJAN",
    "totalUnits": 156,
    "roomMix": {
      "3BR": 78,
      "4BR": 78
    },
    "primaryType": "Villa",
    "offplanUnits": 156,
    "readyUnits": 0,
    "offplanPct": 100.0,
    "freeholdPct": 100.0,
    "avgBuiltUpArea": 272.2,
    "parkingRatio": 2.0,
    "registrationDate": "2026-01-29"
  },
  {
    "name": "Verdana 8",
    "areaDld": "Dubai Investment Park First",
    "areaPcis": "Dubai Investment Park First",
    "totalUnits": 154,
    "roomMix": {
      "2BR": 59,
      "3BR": 23,
      "4BR": 72
    },
    "primaryType": "Villa",
    "offplanUnits": 154,
    "readyUnits": 0,
    "offplanPct": 100.0,
    "freeholdPct": 100.0,
    "avgBuiltUpArea": 203.2,
    "parkingRatio": 1.0,
    "registrationDate": "2026-01-07"
  },
  {
    "name": "Verdana 10",
    "areaDld": "Dubai Investment Park First",
    "areaPcis": "Dubai Investment Park First",
    "totalUnits": 135,
    "roomMix": {
      "2BR": 44,
      "3BR": 19,
      "4BR": 72
    },
    "primaryType": "Villa",
    "offplanUnits": 135,
    "readyUnits": 0,
    "offplanPct": 100.0,
    "freeholdPct": 100.0,
    "avgBuiltUpArea": 207.5,
    "parkingRatio": 1.0,
    "registrationDate": "2026-01-07"
  },
  {
    "name": "Verdana 3",
    "areaDld": "Dubai Investment Park First",
    "areaPcis": "Dubai Investment Park First",
    "totalUnits": 131,
    "roomMix": {
      "2BR": 40,
      "3BR": 19,
      "4BR": 69,
      "5BR": 3
    },
    "primaryType": "Villa",
    "offplanUnits": 131,
    "readyUnits": 0,
    "offplanPct": 100.0,
    "freeholdPct": 100.0,
    "avgBuiltUpArea": 212.3,
    "parkingRatio": 1.0,
    "registrationDate": "2026-01-20"
  },
  {
    "name": "Cedarwood Estates",
    "areaDld": "Me'Aisem First",
    "areaPcis": "Me'Aisem First",
    "totalUnits": 121,
    "roomMix": {
      "4BR": 54,
      "5BR": 28,
      "6BR": 39
    },
    "primaryType": "Villa",
    "offplanUnits": 0,
    "readyUnits": 121,
    "offplanPct": 0.0,
    "freeholdPct": 100.0,
    "avgBuiltUpArea": 692.6,
    "parkingRatio": 2.32,
    "registrationDate": "2026-01-19"
  },
  {
    "name": "Eden Hills",
    "areaDld": "Hadaeq Sheikh Mohammed Bin Rashid",
    "areaPcis": "Hadaeq Sheikh Mohammed Bin Rashid",
    "totalUnits": 113,
    "roomMix": {
      "5BR": 87,
      "6BR": 26
    },
    "primaryType": "Villa",
    "offplanUnits": 113,
    "readyUnits": 0,
    "offplanPct": 100.0,
    "freeholdPct": 100.0,
    "avgBuiltUpArea": 1672.3,
    "parkingRatio": 6.23,
    "registrationDate": "2026-03-02"
  },
  {
    "name": "Nad Al Sheba Gardens Phase 12",
    "areaDld": "Nad Al Shiba First",
    "areaPcis": "Nad Al Shiba First",
    "totalUnits": 97,
    "roomMix": {
      "4BR": 55,
      "5BR": 42
    },
    "primaryType": "Villa",
    "offplanUnits": 0,
    "readyUnits": 97,
    "offplanPct": 0.0,
    "freeholdPct": 100.0,
    "avgBuiltUpArea": 478.6,
    "parkingRatio": 2.43,
    "registrationDate": "2026-01-27"
  },
  {
    "name": "Address Hillcrest",
    "areaDld": "Hadaeq Sheikh Mohammed Bin Rashid",
    "areaPcis": "Hadaeq Sheikh Mohammed Bin Rashid",
    "totalUnits": 49,
    "roomMix": {
      "5BR": 49
    },
    "primaryType": "Villa",
    "offplanUnits": 0,
    "readyUnits": 49,
    "offplanPct": 0.0,
    "freeholdPct": 100.0,
    "avgBuiltUpArea": 944.8,
    "parkingRatio": 3.0,
    "registrationDate": "2026-01-14"
  },
  {
    "name": "DAMAC HILLS (2) - CAMELIA",
    "areaDld": "Madinat Hind 4",
    "areaPcis": "Madinat Hind 4",
    "totalUnits": 42,
    "roomMix": {
      "4BR": 42
    },
    "primaryType": "Villa",
    "offplanUnits": 0,
    "readyUnits": 42,
    "offplanPct": 0.0,
    "freeholdPct": 100.0,
    "avgBuiltUpArea": 221.1,
    "parkingRatio": 2.0,
    "registrationDate": "2026-01-20"
  },
  {
    "name": "La Tilia at Villanova Phase 2",
    "areaDld": "Wadi Al Safa 5",
    "areaPcis": "Wadi Al Safa 5",
    "totalUnits": 42,
    "roomMix": {
      "3BR": 26,
      "4BR": 16
    },
    "primaryType": "Villa",
    "offplanUnits": 42,
    "readyUnits": 0,
    "offplanPct": 100.0,
    "freeholdPct": 100.0,
    "avgBuiltUpArea": 226.0,
    "parkingRatio": 2.0,
    "registrationDate": "2026-01-21"
  },
  {
    "name": "Amis & GPD Presents Fleur De Jardin Villas",
    "areaDld": "Wadi Al Safa 3",
    "areaPcis": "DUBAI LAND RESIDENCE COMPLEX",
    "totalUnits": 25,
    "roomMix": {
      "5BR": 19,
      "6BR": 6
    },
    "primaryType": "Villa",
    "offplanUnits": 25,
    "readyUnits": 0,
    "offplanPct": 100.0,
    "freeholdPct": 100.0,
    "avgBuiltUpArea": 1075.8,
    "parkingRatio": 2.96,
    "registrationDate": "2026-02-12"
  },
  {
    "name": "La Tilia at Villanova Phase 1",
    "areaDld": "Wadi Al Safa 5",
    "areaPcis": "Wadi Al Safa 5",
    "totalUnits": 24,
    "roomMix": {
      "3BR": 14,
      "4BR": 10
    },
    "primaryType": "Villa",
    "offplanUnits": 24,
    "readyUnits": 0,
    "offplanPct": 100.0,
    "freeholdPct": 100.0,
    "avgBuiltUpArea": 223.4,
    "parkingRatio": 2.0,
    "registrationDate": "2026-01-20"
  },
  {
    "name": "TERVA HOMES",
    "areaDld": "Saih Shuaib 2",
    "areaPcis": "DUBAI PRODUCTION CITY",
    "totalUnits": 24,
    "roomMix": {
      "3BR": 20,
      "4BR": 4
    },
    "primaryType": "Villa",
    "offplanUnits": 24,
    "readyUnits": 0,
    "offplanPct": 100.0,
    "freeholdPct": 100.0,
    "avgBuiltUpArea": 215.6,
    "parkingRatio": 1.17,
    "registrationDate": "2026-01-14"
  },
  {
    "name": "The Oasis - Lavita",
    "areaDld": "Me'Aisem Second",
    "areaPcis": "Me'Aisem Second",
    "totalUnits": 6,
    "roomMix": {
      "6BR": 4,
      "7BR": 2
    },
    "primaryType": "Villa",
    "offplanUnits": 0,
    "readyUnits": 6,
    "offplanPct": 0.0,
    "freeholdPct": 100.0,
    "avgBuiltUpArea": 2149.4,
    "parkingRatio": 6.33,
    "registrationDate": "2026-02-17"
  },
  {
    "name": "Emirates Hills",
    "areaDld": "Al Thanayah Fourth",
    "areaPcis": "Al Thanayah Fourth",
    "totalUnits": 3,
    "roomMix": {
      "5BR": 1,
      "6BR": 1,
      "8BR": 1
    },
    "primaryType": "Villa",
    "offplanUnits": 0,
    "readyUnits": 3,
    "offplanPct": 0.0,
    "freeholdPct": 100.0,
    "avgBuiltUpArea": 1613.7,
    "parkingRatio": 3.33,
    "registrationDate": "2026-01-13"
  },
  {
    "name": "Nad Al Sheba Gardens Phase 2",
    "areaDld": "Nad Al Shiba First",
    "areaPcis": "Nad Al Shiba First",
    "totalUnits": 2,
    "roomMix": {
      "3BR": 2
    },
    "primaryType": "Villa",
    "offplanUnits": 0,
    "readyUnits": 2,
    "offplanPct": 0.0,
    "freeholdPct": 100.0,
    "avgBuiltUpArea": 264.3,
    "parkingRatio": 2.0,
    "registrationDate": "2026-02-17"
  },
  {
    "name": "Dubai Hills - Hills View Community",
    "areaDld": "Hadaeq Sheikh Mohammed Bin Rashid",
    "areaPcis": "Hadaeq Sheikh Mohammed Bin Rashid",
    "totalUnits": 1,
    "roomMix": {
      "7BR": 1
    },
    "primaryType": "Villa",
    "offplanUnits": 0,
    "readyUnits": 1,
    "offplanPct": 0.0,
    "freeholdPct": 100.0,
    "avgBuiltUpArea": 3856.5,
    "parkingRatio": 9.0,
    "registrationDate": "2026-03-24"
  }
];

export const REAL_AREA_BUILDINGS: Record<string, AreaBuildingStats> = {
  "Dubai Investment Park First": {
    "totalRegistered": 1573,
    "offplanUnits": 1570,
    "readyUnits": 3,
    "offplanPct": 99.8,
    "roomMix": {
      "Studio": 3,
      "2BR": 516,
      "3BR": 240,
      "4BR": 811,
      "5BR": 3
    },
    "primaryType": "Villa",
    "avgBuiltUpArea": 206.9,
    "parkingRatio": 1.0,
    "projectCount": 7,
    "projects": [
      "Verdana 10",
      "Verdana 3",
      "Verdana 4",
      "Verdana 5",
      "Verdana 6",
      "Verdana 7",
      "Verdana 8"
    ]
  },
  "AL FURJAN": {
    "totalRegistered": 528,
    "offplanUnits": 528,
    "readyUnits": 0,
    "offplanPct": 100.0,
    "roomMix": {
      "3BR": 264,
      "4BR": 264
    },
    "primaryType": "Villa",
    "avgBuiltUpArea": 272.2,
    "parkingRatio": 2.0,
    "projectCount": 3,
    "projects": [
      "The Valley - Alva",
      "The Valley - Alva 2",
      "The Valley - Alva 3"
    ]
  },
  "SILICON OASIS": {
    "totalRegistered": 468,
    "offplanUnits": 468,
    "readyUnits": 0,
    "offplanPct": 100.0,
    "roomMix": {
      "4BR": 236,
      "5BR": 232
    },
    "primaryType": "Villa",
    "avgBuiltUpArea": 251.7,
    "parkingRatio": 2.0,
    "projectCount": 1,
    "projects": [
      "DAMAC ISLANDS 2 - ANTIGUA 1"
    ]
  },
  "Hadaeq Sheikh Mohammed Bin Rashid": {
    "totalRegistered": 163,
    "offplanUnits": 113,
    "readyUnits": 50,
    "offplanPct": 69.3,
    "roomMix": {
      "5BR": 136,
      "6BR": 26,
      "7BR": 1
    },
    "primaryType": "Villa",
    "avgBuiltUpArea": 1467.0,
    "parkingRatio": 5.28,
    "projectCount": 3,
    "projects": [
      "Address Hillcrest",
      "Dubai Hills - Hills View Community",
      "Eden Hills"
    ]
  },
  "Me'Aisem First": {
    "totalRegistered": 122,
    "offplanUnits": 0,
    "readyUnits": 122,
    "offplanPct": 0.0,
    "roomMix": {
      "Studio": 1,
      "4BR": 54,
      "5BR": 28,
      "6BR": 39
    },
    "primaryType": "Villa",
    "avgBuiltUpArea": 686.9,
    "parkingRatio": 2.3,
    "projectCount": 1,
    "projects": [
      "Cedarwood Estates"
    ]
  },
  "Nad Al Shiba First": {
    "totalRegistered": 105,
    "offplanUnits": 0,
    "readyUnits": 105,
    "offplanPct": 0.0,
    "roomMix": {
      "Studio": 1,
      "3BR": 2,
      "4BR": 57,
      "5BR": 43,
      "6BR": 1,
      "7BR": 1
    },
    "primaryType": "Villa",
    "avgBuiltUpArea": 477.5,
    "parkingRatio": 2.38,
    "projectCount": 2,
    "projects": [
      "Nad Al Sheba Gardens Phase 12",
      "Nad Al Sheba Gardens Phase 2"
    ]
  },
  "Wadi Al Safa 5": {
    "totalRegistered": 67,
    "offplanUnits": 66,
    "readyUnits": 1,
    "offplanPct": 98.5,
    "roomMix": {
      "Studio": 1,
      "3BR": 40,
      "4BR": 26
    },
    "primaryType": "Villa",
    "avgBuiltUpArea": 221.7,
    "parkingRatio": 1.97,
    "projectCount": 2,
    "projects": [
      "La Tilia at Villanova Phase 1",
      "La Tilia at Villanova Phase 2"
    ]
  },
  "Madinat Hind 4": {
    "totalRegistered": 42,
    "offplanUnits": 0,
    "readyUnits": 42,
    "offplanPct": 0.0,
    "roomMix": {
      "4BR": 42
    },
    "primaryType": "Villa",
    "avgBuiltUpArea": 221.1,
    "parkingRatio": 2.0,
    "projectCount": 1,
    "projects": [
      "DAMAC HILLS (2) - CAMELIA"
    ]
  },
  "DUBAI PRODUCTION CITY": {
    "totalRegistered": 29,
    "offplanUnits": 24,
    "readyUnits": 5,
    "offplanPct": 82.8,
    "roomMix": {
      "Studio": 3,
      "3BR": 20,
      "4BR": 4,
      "6BR": 1,
      "7BR": 1
    },
    "primaryType": "Villa",
    "avgBuiltUpArea": 242.4,
    "parkingRatio": 1.1,
    "projectCount": 1,
    "projects": [
      "TERVA HOMES"
    ]
  },
  "DUBAI LAND RESIDENCE COMPLEX": {
    "totalRegistered": 25,
    "offplanUnits": 25,
    "readyUnits": 0,
    "offplanPct": 100.0,
    "roomMix": {
      "5BR": 19,
      "6BR": 6
    },
    "primaryType": "Villa",
    "avgBuiltUpArea": 1075.8,
    "parkingRatio": 2.96,
    "projectCount": 1,
    "projects": [
      "Amis & GPD Presents Fleur De Jardin Villas"
    ]
  },
  "Jabal Ali First": {
    "totalRegistered": 13,
    "offplanUnits": 0,
    "readyUnits": 13,
    "offplanPct": 0.0,
    "roomMix": {
      "4BR": 9,
      "5BR": 2,
      "6BR": 1,
      "7BR": 1
    },
    "primaryType": "Villa",
    "avgBuiltUpArea": 456.1,
    "parkingRatio": 2.0,
    "projectCount": 0,
    "projects": []
  },
  "Wadi Al Safa 2": {
    "totalRegistered": 7,
    "offplanUnits": 0,
    "readyUnits": 7,
    "offplanPct": 0.0,
    "roomMix": {
      "Studio": 7
    },
    "primaryType": "Building",
    "avgBuiltUpArea": 0.0,
    "parkingRatio": 0.0,
    "projectCount": 0,
    "projects": []
  },
  "Me'Aisem Second": {
    "totalRegistered": 6,
    "offplanUnits": 0,
    "readyUnits": 6,
    "offplanPct": 0.0,
    "roomMix": {
      "6BR": 4,
      "7BR": 2
    },
    "primaryType": "Villa",
    "avgBuiltUpArea": 2149.4,
    "parkingRatio": 6.33,
    "projectCount": 1,
    "projects": [
      "The Oasis - Lavita"
    ]
  },
  "Al Khawaneej First": {
    "totalRegistered": 6,
    "offplanUnits": 0,
    "readyUnits": 6,
    "offplanPct": 0.0,
    "roomMix": {
      "5BR": 6
    },
    "primaryType": "Villa",
    "avgBuiltUpArea": 734.8,
    "parkingRatio": 2.0,
    "projectCount": 0,
    "projects": []
  },
  "Al Rowaiyah Second": {
    "totalRegistered": 6,
    "offplanUnits": 0,
    "readyUnits": 6,
    "offplanPct": 0.0,
    "roomMix": {
      "Studio": 6
    },
    "primaryType": "Education",
    "avgBuiltUpArea": 18448.7,
    "parkingRatio": 14.17,
    "projectCount": 0,
    "projects": []
  },
  "Saih Shuaib 4": {
    "totalRegistered": 5,
    "offplanUnits": 0,
    "readyUnits": 5,
    "offplanPct": 0.0,
    "roomMix": {
      "Studio": 5
    },
    "primaryType": "Building",
    "avgBuiltUpArea": 0.0,
    "parkingRatio": 0.0,
    "projectCount": 0,
    "projects": []
  },
  "Warsan Fourth": {
    "totalRegistered": 4,
    "offplanUnits": 0,
    "readyUnits": 4,
    "offplanPct": 0.0,
    "roomMix": {
      "Studio": 4
    },
    "primaryType": "Building",
    "avgBuiltUpArea": 0.0,
    "parkingRatio": 0.0,
    "projectCount": 0,
    "projects": []
  },
  "Al Satwa": {
    "totalRegistered": 4,
    "offplanUnits": 0,
    "readyUnits": 4,
    "offplanPct": 0.0,
    "roomMix": {
      "Studio": 4
    },
    "primaryType": "Building",
    "avgBuiltUpArea": 2612.0,
    "parkingRatio": 0.0,
    "projectCount": 0,
    "projects": []
  },
  "Al Thanayah Fourth": {
    "totalRegistered": 3,
    "offplanUnits": 0,
    "readyUnits": 3,
    "offplanPct": 0.0,
    "roomMix": {
      "5BR": 1,
      "6BR": 1,
      "8BR": 1
    },
    "primaryType": "Villa",
    "avgBuiltUpArea": 1613.7,
    "parkingRatio": 3.33,
    "projectCount": 1,
    "projects": [
      "Emirates Hills"
    ]
  },
  "TECOM SITE A": {
    "totalRegistered": 3,
    "offplanUnits": 0,
    "readyUnits": 3,
    "offplanPct": 0.0,
    "roomMix": {
      "5BR": 2,
      "6BR": 1
    },
    "primaryType": "Villa",
    "avgBuiltUpArea": 746.2,
    "parkingRatio": 2.0,
    "projectCount": 0,
    "projects": []
  },
  "Al Barsha Third": {
    "totalRegistered": 3,
    "offplanUnits": 0,
    "readyUnits": 3,
    "offplanPct": 0.0,
    "roomMix": {
      "Studio": 1,
      "5BR": 2
    },
    "primaryType": "Villa",
    "avgBuiltUpArea": 350.7,
    "parkingRatio": 1.33,
    "projectCount": 0,
    "projects": []
  },
  "Madinat Al Mataar": {
    "totalRegistered": 2,
    "offplanUnits": 0,
    "readyUnits": 2,
    "offplanPct": 0.0,
    "roomMix": {
      "Studio": 1,
      "5BR": 1
    },
    "primaryType": "Building",
    "avgBuiltUpArea": 288.5,
    "parkingRatio": 1.0,
    "projectCount": 0,
    "projects": []
  },
  "Palm Jumeirah": {
    "totalRegistered": 2,
    "offplanUnits": 0,
    "readyUnits": 2,
    "offplanPct": 0.0,
    "roomMix": {
      "3BR": 1,
      "5BR": 1
    },
    "primaryType": "Villa",
    "avgBuiltUpArea": 2172.7,
    "parkingRatio": 7.5,
    "projectCount": 0,
    "projects": []
  },
  "DUBAI HILLS": {
    "totalRegistered": 2,
    "offplanUnits": 0,
    "readyUnits": 2,
    "offplanPct": 0.0,
    "roomMix": {
      "5BR": 2
    },
    "primaryType": "Villa",
    "avgBuiltUpArea": 636.2,
    "parkingRatio": 2.0,
    "projectCount": 0,
    "projects": []
  },
  "Nad Al Hamar": {
    "totalRegistered": 1,
    "offplanUnits": 0,
    "readyUnits": 1,
    "offplanPct": 0.0,
    "roomMix": {
      "Studio": 1
    },
    "primaryType": "Building",
    "avgBuiltUpArea": 0.0,
    "parkingRatio": 0.0,
    "projectCount": 0,
    "projects": []
  },
  "Ras Al Khor Industrial Second": {
    "totalRegistered": 1,
    "offplanUnits": 0,
    "readyUnits": 1,
    "offplanPct": 0.0,
    "roomMix": {
      "Studio": 1
    },
    "primaryType": "Building",
    "avgBuiltUpArea": 0.0,
    "parkingRatio": 0.0,
    "projectCount": 0,
    "projects": []
  },
  "Jumeirah First": {
    "totalRegistered": 1,
    "offplanUnits": 0,
    "readyUnits": 1,
    "offplanPct": 0.0,
    "roomMix": {
      "4BR": 1
    },
    "primaryType": "Villa",
    "avgBuiltUpArea": 891.6,
    "parkingRatio": 3.0,
    "projectCount": 0,
    "projects": []
  },
  "Jabal Ali Industrial First": {
    "totalRegistered": 1,
    "offplanUnits": 0,
    "readyUnits": 1,
    "offplanPct": 0.0,
    "roomMix": {
      "Studio": 1
    },
    "primaryType": "Building",
    "avgBuiltUpArea": 0.0,
    "parkingRatio": 0.0,
    "projectCount": 0,
    "projects": []
  },
  "ARJAN": {
    "totalRegistered": 1,
    "offplanUnits": 0,
    "readyUnits": 1,
    "offplanPct": 0.0,
    "roomMix": {
      "Studio": 1
    },
    "primaryType": "Building",
    "avgBuiltUpArea": 0.0,
    "parkingRatio": 0.0,
    "projectCount": 0,
    "projects": []
  },
  "Nadd Hessa": {
    "totalRegistered": 1,
    "offplanUnits": 0,
    "readyUnits": 1,
    "offplanPct": 0.0,
    "roomMix": {
      "Studio": 1
    },
    "primaryType": "Building",
    "avgBuiltUpArea": 10000.0,
    "parkingRatio": 0.0,
    "projectCount": 0,
    "projects": []
  },
  "Al Barshaa South Third": {
    "totalRegistered": 1,
    "offplanUnits": 0,
    "readyUnits": 1,
    "offplanPct": 0.0,
    "roomMix": {
      "Studio": 1
    },
    "primaryType": "Building",
    "avgBuiltUpArea": 0.0,
    "parkingRatio": 0.0,
    "projectCount": 0,
    "projects": []
  },
  "Al Warsan Second": {
    "totalRegistered": 1,
    "offplanUnits": 0,
    "readyUnits": 1,
    "offplanPct": 0.0,
    "roomMix": {
      "Studio": 1
    },
    "primaryType": "Building",
    "avgBuiltUpArea": 0.0,
    "parkingRatio": 0.0,
    "projectCount": 0,
    "projects": []
  },
  "Al Wasl": {
    "totalRegistered": 1,
    "offplanUnits": 0,
    "readyUnits": 1,
    "offplanPct": 0.0,
    "roomMix": {
      "3BR": 1
    },
    "primaryType": "Villa",
    "avgBuiltUpArea": 212.0,
    "parkingRatio": 3.0,
    "projectCount": 0,
    "projects": []
  }
};

export const REAL_MARKET_BUILDING_STATS: MarketBuildingStats = {
  "totalRegistrations": 3197,
  "offplanRegistrations": 2794,
  "readyRegistrations": 403,
  "offplanPct": 87.4,
  "uniqueProjects": 24,
  "uniqueAreas": 33,
  "avgBuiltUpArea": 371.6,
  "topRoomType": "4 B/R",
  "dataDate": "Q1 2026"
};

// Helper functions
export function getProjectUnits(projectName: string): ProjectUnitDetail | undefined {
  return REAL_PROJECT_UNITS.find(p =>
    p.name.toLowerCase() === projectName.toLowerCase()
  );
}

export function getProjectsByArea(areaPcis: string): ProjectUnitDetail[] {
  return REAL_PROJECT_UNITS.filter(p =>
    p.areaPcis.toLowerCase() === areaPcis.toLowerCase()
  );
}

export function getAreaBuildingStats(areaPcis: string): AreaBuildingStats | undefined {
  return REAL_AREA_BUILDINGS[areaPcis];
}
