// PCIS Transaction Intelligence - Mock Data
// Dubai Land Department API structure
// Ready for swap to real DLD Open Data API

export interface Transaction {
  id: string
  date: string                    // ISO date
  area: string                    // area name
  areaId: string                  // links to area profiles
  subArea?: string
  building: string
  unitNumber?: string
  propertyType: 'Villa' | 'Apartment' | 'Penthouse' | 'Townhouse' | 'Land' | 'Office' | 'Retail'
  bedrooms: number
  size: number                    // sqft
  transactionValue: number        // AED
  priceSqft: number
  transactionType: 'Sale' | 'Mortgage' | 'Gift'
  usageType: 'Residential' | 'Commercial'
  isOffPlan: boolean
  registrationStatus: 'Registered' | 'Pending'
  buyerNationality: string
  sellerNationality?: string
  paymentMethod: 'Cash' | 'Mortgage'
  mortgageProvider?: string
  // Computed context
  areaAvgPriceSqft: number
  buildingAvgPriceSqft?: number
  priceVsAreaAvg: number          // percent above/below area average
  priceVsBuildingAvg?: number
}

export interface VolumeByPeriod {
  period: string                  // "2026-03", "2026-W12", "2026-03-24"
  transactions: number
  totalValue: number
  avgValue: number
  offPlanPct: number
  cashPct: number
}

export interface VolumeByArea {
  area: string
  areaId: string
  transactions: number
  totalValue: number
  avgPriceSqft: number
  momChange: number               // month-on-month percent
  yoyChange: number               // year-on-year percent
}

export interface VolumeByType {
  propertyType: string
  transactions: number
  totalValue: number
  avgValue: number
  pctOfTotal: number
}

export interface BuyerProfile {
  nationality: string
  transactionCount: number
  totalValue: number
  avgTransactionValue: number
  cashPct: number
  preferredAreas: string[]
  preferredTypes: string[]
  goldenVisaEligiblePct: number   // % of transactions above 2M AED
  trend: 'increasing' | 'stable' | 'decreasing'
  momChange: number
}

export interface BuildingAnalytics {
  building: string
  area: string
  areaId: string
  totalTransactions: number
  avgPriceSqft: number
  priceTrend: number[]            // 12 months
  lastTransactionDate: string
  lastTransactionPrice: number
  priceVsAreaAvg: number          // percent
  topBuyerNationalities: { nationality: string; pct: number }[]
  transactions: Transaction[]      // recent transactions in this building
}

export interface TransactionSummary {
  totalTransactions: number
  totalValue: number
  avgTransactionValue: number
  avgPriceSqft: number
  offPlanPct: number
  cashPct: number
  topArea: string
  topNationality: string
  momVolumeChange: number
  yoyVolumeChange: number
}

// ===================== MOCK DATA =====================

const AREA_AVG_PRICE_SQFT: Record<string, number> = {
  'palm-jumeirah': 3850,
  'dubai-marina': 2150,
  'downtown-dubai': 2800,
  'emirates-hills': 4200,
  'business-bay': 1850,
  'dubai-hills-estate': 2450,
  'difc': 2650,
  'dubai-south': 850,
  'jbr': 2350,
  'mbr-city': 1650,
  'jge': 1950,
}

const NATIONALITIES = [
  'Indian', 'British', 'Russian', 'Emirati', 'Chinese',
  'Pakistani', 'French', 'Saudi', 'German', 'American',
  'Filipino', 'Lebanese', 'Canadian', 'Italian', 'Egyptian'
]

const BUILDINGS: Record<string, { area: string; areaId: string }> = {
  'Atlantis The Royal Residences': { area: 'Palm Jumeirah', areaId: 'palm-jumeirah' },
  'One at Palm Jumeirah': { area: 'Palm Jumeirah', areaId: 'palm-jumeirah' },
  'Princess Tower': { area: 'Dubai Marina', areaId: 'dubai-marina' },
  'Burj Khalifa': { area: 'Downtown Dubai', areaId: 'downtown-dubai' },
  'Address Downtown': { area: 'Downtown Dubai', areaId: 'downtown-dubai' },
  'The Opus': { area: 'Business Bay', areaId: 'business-bay' },
  'Marina Gate': { area: 'Dubai Marina', areaId: 'dubai-marina' },
  'Emerald Residence': { area: 'Business Bay', areaId: 'business-bay' },
  'Dubai Heights': { area: 'Business Bay', areaId: 'business-bay' },
  'Vida Residence': { area: 'Business Bay', areaId: 'business-bay' },
  'Serenia Residences': { area: 'Dubai South', areaId: 'dubai-south' },
  'Rimal JBR': { area: 'JBR', areaId: 'jbr' },
  'Golden Crescent': { area: 'JBR', areaId: 'jbr' },
  'DAMAC Hills Villas': { area: 'Dubai Hills Estate', areaId: 'dubai-hills-estate' },
  'Sobha Hartland Greens': { area: 'Dubai Hills Estate', areaId: 'dubai-hills-estate' },
  'District One Villas': { area: 'Emirates Hills', areaId: 'emirates-hills' },
  'Emirates Hills Villas': { area: 'Emirates Hills', areaId: 'emirates-hills' },
  'One Central DIFC': { area: 'DIFC', areaId: 'difc' },
  'MBR City Residences': { area: 'MBR City', areaId: 'mbr-city' },
  'Azizi Riviera': { area: 'MBR City', areaId: 'mbr-city' },
}

// Generate random dates in last 90 days
function generateTransactionDate(): string {
  const end = new Date('2026-03-24')
  const start = new Date('2025-12-25')
  const randomTime = start.getTime() + Math.random() * (end.getTime() - start.getTime())
  return new Date(randomTime).toISOString().split('T')[0]
}

// Helper to get random item from array
function randomItem<T>(arr: T[]): T {
  return arr[Math.floor(Math.random() * arr.length)]
}

// Helper for weighted random selection
function weightedRandom(weights: Record<string, number>): string {
  const keys = Object.keys(weights)
  const values = keys.map(k => weights[k])
  const sum = values.reduce((a, b) => a + b, 0)
  let random = Math.random() * sum
  for (let i = 0; i < keys.length; i++) {
    random -= values[i]
    if (random <= 0) return keys[i]
  }
  return keys[keys.length - 1]
}

// Generate individual transactions
const transactionsData: Transaction[] = [
  // Palm Jumeirah (8 txns)
  {
    id: 'TXN-001',
    date: '2026-03-22',
    area: 'Palm Jumeirah',
    areaId: 'palm-jumeirah',
    building: 'One at Palm Jumeirah',
    unitNumber: 'PH-501',
    propertyType: 'Penthouse',
    bedrooms: 4,
    size: 5200,
    transactionValue: 85000000,
    priceSqft: 16346,
    transactionType: 'Sale',
    usageType: 'Residential',
    isOffPlan: false,
    registrationStatus: 'Registered',
    buyerNationality: 'British',
    paymentMethod: 'Cash',
    areaAvgPriceSqft: 3850,
    priceVsAreaAvg: 324,
  },
  {
    id: 'TXN-002',
    date: '2026-03-20',
    area: 'Palm Jumeirah',
    areaId: 'palm-jumeirah',
    building: 'Atlantis The Royal Residences',
    unitNumber: 'AP-1204',
    propertyType: 'Apartment',
    bedrooms: 3,
    size: 2800,
    transactionValue: 18500000,
    priceSqft: 6607,
    transactionType: 'Sale',
    usageType: 'Residential',
    isOffPlan: false,
    registrationStatus: 'Registered',
    buyerNationality: 'Russian',
    paymentMethod: 'Cash',
    areaAvgPriceSqft: 3850,
    priceVsAreaAvg: 72,
  },
  {
    id: 'TXN-003',
    date: '2026-03-18',
    area: 'Palm Jumeirah',
    areaId: 'palm-jumeirah',
    building: 'One at Palm Jumeirah',
    unitNumber: 'V-008',
    propertyType: 'Villa',
    bedrooms: 5,
    size: 8500,
    transactionValue: 125000000,
    priceSqft: 14706,
    transactionType: 'Sale',
    usageType: 'Residential',
    isOffPlan: false,
    registrationStatus: 'Registered',
    buyerNationality: 'Emirati',
    paymentMethod: 'Cash',
    areaAvgPriceSqft: 3850,
    priceVsAreaAvg: 282,
  },
  {
    id: 'TXN-004',
    date: '2026-03-15',
    area: 'Palm Jumeirah',
    areaId: 'palm-jumeirah',
    building: 'Atlantis The Royal Residences',
    unitNumber: 'PH-2101',
    propertyType: 'Penthouse',
    bedrooms: 4,
    size: 4200,
    transactionValue: 52000000,
    priceSqft: 12381,
    transactionType: 'Mortgage',
    usageType: 'Residential',
    isOffPlan: false,
    registrationStatus: 'Registered',
    buyerNationality: 'Indian',
    paymentMethod: 'Mortgage',
    mortgageProvider: 'ADIB',
    areaAvgPriceSqft: 3850,
    priceVsAreaAvg: 222,
  },
  {
    id: 'TXN-005',
    date: '2026-03-12',
    area: 'Palm Jumeirah',
    areaId: 'palm-jumeirah',
    building: 'One at Palm Jumeirah',
    unitNumber: 'AP-805',
    propertyType: 'Apartment',
    bedrooms: 2,
    size: 1850,
    transactionValue: 9800000,
    priceSqft: 5297,
    transactionType: 'Sale',
    usageType: 'Residential',
    isOffPlan: false,
    registrationStatus: 'Registered',
    buyerNationality: 'French',
    paymentMethod: 'Cash',
    areaAvgPriceSqft: 3850,
    priceVsAreaAvg: 38,
  },
  {
    id: 'TXN-006',
    date: '2026-03-08',
    area: 'Palm Jumeirah',
    areaId: 'palm-jumeirah',
    building: 'Atlantis The Royal Residences',
    unitNumber: 'V-015',
    propertyType: 'Villa',
    bedrooms: 6,
    size: 9200,
    transactionValue: 185000000,
    priceSqft: 20109,
    transactionType: 'Sale',
    usageType: 'Residential',
    isOffPlan: false,
    registrationStatus: 'Registered',
    buyerNationality: 'Saudi',
    paymentMethod: 'Cash',
    areaAvgPriceSqft: 3850,
    priceVsAreaAvg: 423,
  },
  {
    id: 'TXN-007',
    date: '2026-03-05',
    area: 'Palm Jumeirah',
    areaId: 'palm-jumeirah',
    building: 'One at Palm Jumeirah',
    unitNumber: 'PH-3301',
    propertyType: 'Penthouse',
    bedrooms: 5,
    size: 5800,
    transactionValue: 68000000,
    priceSqft: 11724,
    transactionType: 'Sale',
    usageType: 'Residential',
    isOffPlan: false,
    registrationStatus: 'Registered',
    buyerNationality: 'Chinese',
    paymentMethod: 'Mortgage',
    mortgageProvider: 'FAB',
    areaAvgPriceSqft: 3850,
    priceVsAreaAvg: 205,
  },
  {
    id: 'TXN-008',
    date: '2026-02-28',
    area: 'Palm Jumeirah',
    areaId: 'palm-jumeirah',
    building: 'Atlantis The Royal Residences',
    unitNumber: 'AP-1508',
    propertyType: 'Apartment',
    bedrooms: 3,
    size: 2650,
    transactionValue: 15200000,
    priceSqft: 5736,
    transactionType: 'Sale',
    usageType: 'Residential',
    isOffPlan: false,
    registrationStatus: 'Registered',
    buyerNationality: 'Russian',
    paymentMethod: 'Cash',
    areaAvgPriceSqft: 3850,
    priceVsAreaAvg: 49,
  },

  // Dubai Marina (10 txns)
  {
    id: 'TXN-009',
    date: '2026-03-23',
    area: 'Dubai Marina',
    areaId: 'dubai-marina',
    building: 'Princess Tower',
    unitNumber: 'AP-2505',
    propertyType: 'Apartment',
    bedrooms: 2,
    size: 1400,
    transactionValue: 4500000,
    priceSqft: 3214,
    transactionType: 'Sale',
    usageType: 'Residential',
    isOffPlan: false,
    registrationStatus: 'Registered',
    buyerNationality: 'Indian',
    paymentMethod: 'Mortgage',
    mortgageProvider: 'ENBD',
    areaAvgPriceSqft: 2150,
    priceVsAreaAvg: 49,
  },
  {
    id: 'TXN-010',
    date: '2026-03-21',
    area: 'Dubai Marina',
    areaId: 'dubai-marina',
    building: 'Marina Gate',
    unitNumber: 'PH-6201',
    propertyType: 'Penthouse',
    bedrooms: 4,
    size: 3800,
    transactionValue: 28000000,
    priceSqft: 7368,
    transactionType: 'Sale',
    usageType: 'Residential',
    isOffPlan: false,
    registrationStatus: 'Registered',
    buyerNationality: 'British',
    paymentMethod: 'Cash',
    areaAvgPriceSqft: 2150,
    priceVsAreaAvg: 243,
  },
  {
    id: 'TXN-011',
    date: '2026-03-19',
    area: 'Dubai Marina',
    areaId: 'dubai-marina',
    building: 'Princess Tower',
    unitNumber: 'AP-1802',
    propertyType: 'Apartment',
    bedrooms: 3,
    size: 1950,
    transactionValue: 6800000,
    priceSqft: 3487,
    transactionType: 'Sale',
    usageType: 'Residential',
    isOffPlan: false,
    registrationStatus: 'Registered',
    buyerNationality: 'Pakistani',
    paymentMethod: 'Mortgage',
    mortgageProvider: 'ADIB',
    areaAvgPriceSqft: 2150,
    priceVsAreaAvg: 62,
  },
  {
    id: 'TXN-012',
    date: '2026-03-17',
    area: 'Dubai Marina',
    areaId: 'dubai-marina',
    building: 'Marina Gate',
    unitNumber: 'AP-3205',
    propertyType: 'Apartment',
    bedrooms: 2,
    size: 1200,
    transactionValue: 3200000,
    priceSqft: 2667,
    transactionType: 'Sale',
    usageType: 'Residential',
    isOffPlan: false,
    registrationStatus: 'Registered',
    buyerNationality: 'Indian',
    paymentMethod: 'Mortgage',
    mortgageProvider: 'FAB',
    areaAvgPriceSqft: 2150,
    priceVsAreaAvg: 24,
  },
  {
    id: 'TXN-013',
    date: '2026-03-14',
    area: 'Dubai Marina',
    areaId: 'dubai-marina',
    building: 'Princess Tower',
    unitNumber: 'PH-5205',
    propertyType: 'Penthouse',
    bedrooms: 3,
    size: 2800,
    transactionValue: 15500000,
    priceSqft: 5536,
    transactionType: 'Sale',
    usageType: 'Residential',
    isOffPlan: false,
    registrationStatus: 'Registered',
    buyerNationality: 'Russian',
    paymentMethod: 'Cash',
    areaAvgPriceSqft: 2150,
    priceVsAreaAvg: 157,
  },
  {
    id: 'TXN-014',
    date: '2026-03-11',
    area: 'Dubai Marina',
    areaId: 'dubai-marina',
    building: 'Rimal JBR',
    unitNumber: 'AP-1103',
    propertyType: 'Apartment',
    bedrooms: 2,
    size: 1550,
    transactionValue: 5200000,
    priceSqft: 3355,
    transactionType: 'Sale',
    usageType: 'Residential',
    isOffPlan: false,
    registrationStatus: 'Registered',
    buyerNationality: 'Filipino',
    paymentMethod: 'Mortgage',
    mortgageProvider: 'ENBD',
    areaAvgPriceSqft: 2150,
    priceVsAreaAvg: 56,
  },
  {
    id: 'TXN-015',
    date: '2026-03-09',
    area: 'Dubai Marina',
    areaId: 'dubai-marina',
    building: 'Marina Gate',
    unitNumber: 'AP-2208',
    propertyType: 'Apartment',
    bedrooms: 3,
    size: 2100,
    transactionValue: 7800000,
    priceSqft: 3714,
    transactionType: 'Mortgage',
    usageType: 'Residential',
    isOffPlan: false,
    registrationStatus: 'Registered',
    buyerNationality: 'Lebanese',
    paymentMethod: 'Mortgage',
    mortgageProvider: 'ADIB',
    areaAvgPriceSqft: 2150,
    priceVsAreaAvg: 73,
  },
  {
    id: 'TXN-016',
    date: '2026-03-06',
    area: 'Dubai Marina',
    areaId: 'dubai-marina',
    building: 'Princess Tower',
    unitNumber: 'AP-4102',
    propertyType: 'Apartment',
    bedrooms: 1,
    size: 850,
    transactionValue: 1900000,
    priceSqft: 2235,
    transactionType: 'Sale',
    usageType: 'Residential',
    isOffPlan: false,
    registrationStatus: 'Registered',
    buyerNationality: 'Indian',
    paymentMethod: 'Mortgage',
    mortgageProvider: 'FAB',
    areaAvgPriceSqft: 2150,
    priceVsAreaAvg: 4,
  },
  {
    id: 'TXN-017',
    date: '2026-03-03',
    area: 'Dubai Marina',
    areaId: 'dubai-marina',
    building: 'Marina Gate',
    unitNumber: 'AP-1505',
    propertyType: 'Apartment',
    bedrooms: 2,
    size: 1480,
    transactionValue: 4200000,
    priceSqft: 2838,
    transactionType: 'Sale',
    usageType: 'Residential',
    isOffPlan: false,
    registrationStatus: 'Registered',
    buyerNationality: 'British',
    paymentMethod: 'Cash',
    areaAvgPriceSqft: 2150,
    priceVsAreaAvg: 32,
  },
  {
    id: 'TXN-018',
    date: '2026-02-27',
    area: 'Dubai Marina',
    areaId: 'dubai-marina',
    building: 'Princess Tower',
    unitNumber: 'PH-3301',
    propertyType: 'Penthouse',
    bedrooms: 3,
    size: 3200,
    transactionValue: 18500000,
    priceSqft: 5781,
    transactionType: 'Sale',
    usageType: 'Residential',
    isOffPlan: false,
    registrationStatus: 'Registered',
    buyerNationality: 'Chinese',
    paymentMethod: 'Cash',
    areaAvgPriceSqft: 2150,
    priceVsAreaAvg: 169,
  },

  // Downtown Dubai (8 txns)
  {
    id: 'TXN-019',
    date: '2026-03-24',
    area: 'Downtown Dubai',
    areaId: 'downtown-dubai',
    building: 'Burj Khalifa',
    unitNumber: 'AP-5601',
    propertyType: 'Apartment',
    bedrooms: 3,
    size: 2200,
    transactionValue: 9800000,
    priceSqft: 4455,
    transactionType: 'Sale',
    usageType: 'Residential',
    isOffPlan: false,
    registrationStatus: 'Registered',
    buyerNationality: 'Russian',
    paymentMethod: 'Cash',
    areaAvgPriceSqft: 2800,
    priceVsAreaAvg: 59,
  },
  {
    id: 'TXN-020',
    date: '2026-03-22',
    area: 'Downtown Dubai',
    areaId: 'downtown-dubai',
    building: 'Address Downtown',
    unitNumber: 'PH-6805',
    propertyType: 'Penthouse',
    bedrooms: 4,
    size: 4500,
    transactionValue: 42000000,
    priceSqft: 9333,
    transactionType: 'Sale',
    usageType: 'Residential',
    isOffPlan: false,
    registrationStatus: 'Registered',
    buyerNationality: 'Emirati',
    paymentMethod: 'Cash',
    areaAvgPriceSqft: 2800,
    priceVsAreaAvg: 234,
  },
  {
    id: 'TXN-021',
    date: '2026-03-20',
    area: 'Downtown Dubai',
    areaId: 'downtown-dubai',
    building: 'Burj Khalifa',
    unitNumber: 'AP-2808',
    propertyType: 'Apartment',
    bedrooms: 2,
    size: 1600,
    transactionValue: 5800000,
    priceSqft: 3625,
    transactionType: 'Sale',
    usageType: 'Residential',
    isOffPlan: false,
    registrationStatus: 'Registered',
    buyerNationality: 'Indian',
    paymentMethod: 'Mortgage',
    mortgageProvider: 'ADIB',
    areaAvgPriceSqft: 2800,
    priceVsAreaAvg: 29,
  },
  {
    id: 'TXN-022',
    date: '2026-03-16',
    area: 'Downtown Dubai',
    areaId: 'downtown-dubai',
    building: 'Address Downtown',
    unitNumber: 'AP-3402',
    propertyType: 'Apartment',
    bedrooms: 3,
    size: 2400,
    transactionValue: 8200000,
    priceSqft: 3417,
    transactionType: 'Sale',
    usageType: 'Residential',
    isOffPlan: false,
    registrationStatus: 'Registered',
    buyerNationality: 'Pakistani',
    paymentMethod: 'Mortgage',
    mortgageProvider: 'FAB',
    areaAvgPriceSqft: 2800,
    priceVsAreaAvg: 22,
  },
  {
    id: 'TXN-023',
    date: '2026-03-13',
    area: 'Downtown Dubai',
    areaId: 'downtown-dubai',
    building: 'Burj Khalifa',
    unitNumber: 'PH-16301',
    propertyType: 'Penthouse',
    bedrooms: 5,
    size: 6200,
    transactionValue: 68000000,
    priceSqft: 10968,
    transactionType: 'Sale',
    usageType: 'Residential',
    isOffPlan: false,
    registrationStatus: 'Registered',
    buyerNationality: 'British',
    paymentMethod: 'Cash',
    areaAvgPriceSqft: 2800,
    priceVsAreaAvg: 292,
  },
  {
    id: 'TXN-024',
    date: '2026-03-10',
    area: 'Downtown Dubai',
    areaId: 'downtown-dubai',
    building: 'Address Downtown',
    unitNumber: 'AP-2105',
    propertyType: 'Apartment',
    bedrooms: 2,
    size: 1750,
    transactionValue: 6500000,
    priceSqft: 3714,
    transactionType: 'Sale',
    usageType: 'Residential',
    isOffPlan: false,
    registrationStatus: 'Registered',
    buyerNationality: 'French',
    paymentMethod: 'Mortgage',
    mortgageProvider: 'ENBD',
    areaAvgPriceSqft: 2800,
    priceVsAreaAvg: 33,
  },
  {
    id: 'TXN-025',
    date: '2026-03-07',
    area: 'Downtown Dubai',
    areaId: 'downtown-dubai',
    building: 'Burj Khalifa',
    unitNumber: 'AP-8505',
    propertyType: 'Apartment',
    bedrooms: 3,
    size: 2350,
    transactionValue: 11200000,
    priceSqft: 4766,
    transactionType: 'Mortgage',
    usageType: 'Residential',
    isOffPlan: false,
    registrationStatus: 'Registered',
    buyerNationality: 'Saudi',
    paymentMethod: 'Mortgage',
    mortgageProvider: 'ADIB',
    areaAvgPriceSqft: 2800,
    priceVsAreaAvg: 70,
  },
  {
    id: 'TXN-026',
    date: '2026-03-04',
    area: 'Downtown Dubai',
    areaId: 'downtown-dubai',
    building: 'Address Downtown',
    unitNumber: 'PH-5505',
    propertyType: 'Penthouse',
    bedrooms: 4,
    size: 4200,
    transactionValue: 38000000,
    priceSqft: 9048,
    transactionType: 'Sale',
    usageType: 'Residential',
    isOffPlan: false,
    registrationStatus: 'Registered',
    buyerNationality: 'Chinese',
    paymentMethod: 'Cash',
    areaAvgPriceSqft: 2800,
    priceVsAreaAvg: 223,
  },

  // Business Bay (10 txns)
  {
    id: 'TXN-027',
    date: '2026-03-23',
    area: 'Business Bay',
    areaId: 'business-bay',
    building: 'The Opus',
    unitNumber: 'AP-1402',
    propertyType: 'Apartment',
    bedrooms: 2,
    size: 1200,
    transactionValue: 2800000,
    priceSqft: 2333,
    transactionType: 'Sale',
    usageType: 'Residential',
    isOffPlan: false,
    registrationStatus: 'Registered',
    buyerNationality: 'Indian',
    paymentMethod: 'Mortgage',
    mortgageProvider: 'FAB',
    areaAvgPriceSqft: 1850,
    priceVsAreaAvg: 26,
  },
  {
    id: 'TXN-028',
    date: '2026-03-21',
    area: 'Business Bay',
    areaId: 'business-bay',
    building: 'Emerald Residence',
    unitNumber: 'AP-2805',
    propertyType: 'Apartment',
    bedrooms: 3,
    size: 1850,
    transactionValue: 4100000,
    priceSqft: 2216,
    transactionType: 'Sale',
    usageType: 'Residential',
    isOffPlan: false,
    registrationStatus: 'Registered',
    buyerNationality: 'Pakistani',
    paymentMethod: 'Mortgage',
    mortgageProvider: 'ENBD',
    areaAvgPriceSqft: 1850,
    priceVsAreaAvg: 20,
  },
  {
    id: 'TXN-029',
    date: '2026-03-19',
    area: 'Business Bay',
    areaId: 'business-bay',
    building: 'Dubai Heights',
    unitNumber: 'AP-1108',
    propertyType: 'Apartment',
    bedrooms: 2,
    size: 1400,
    transactionValue: 2650000,
    priceSqft: 1893,
    transactionType: 'Sale',
    usageType: 'Residential',
    isOffPlan: false,
    registrationStatus: 'Registered',
    buyerNationality: 'Indian',
    paymentMethod: 'Mortgage',
    mortgageProvider: 'ADIB',
    areaAvgPriceSqft: 1850,
    priceVsAreaAvg: 2,
  },
  {
    id: 'TXN-030',
    date: '2026-03-17',
    area: 'Business Bay',
    areaId: 'business-bay',
    building: 'The Opus',
    unitNumber: 'PH-6505',
    propertyType: 'Penthouse',
    bedrooms: 3,
    size: 2600,
    transactionValue: 8000000,
    priceSqft: 3077,
    transactionType: 'Sale',
    usageType: 'Residential',
    isOffPlan: false,
    registrationStatus: 'Registered',
    buyerNationality: 'British',
    paymentMethod: 'Cash',
    areaAvgPriceSqft: 1850,
    priceVsAreaAvg: 66,
  },
  {
    id: 'TXN-031',
    date: '2026-03-14',
    area: 'Business Bay',
    areaId: 'business-bay',
    building: 'Vida Residence',
    unitNumber: 'AP-3102',
    propertyType: 'Apartment',
    bedrooms: 2,
    size: 1300,
    transactionValue: 2500000,
    priceSqft: 1923,
    transactionType: 'Sale',
    usageType: 'Residential',
    isOffPlan: false,
    registrationStatus: 'Registered',
    buyerNationality: 'Filipino',
    paymentMethod: 'Mortgage',
    mortgageProvider: 'FAB',
    areaAvgPriceSqft: 1850,
    priceVsAreaAvg: 4,
  },
  {
    id: 'TXN-032',
    date: '2026-03-11',
    area: 'Business Bay',
    areaId: 'business-bay',
    building: 'Emerald Residence',
    unitNumber: 'AP-1502',
    propertyType: 'Apartment',
    bedrooms: 1,
    size: 850,
    transactionValue: 1600000,
    priceSqft: 1882,
    transactionType: 'Sale',
    usageType: 'Residential',
    isOffPlan: false,
    registrationStatus: 'Registered',
    buyerNationality: 'Indian',
    paymentMethod: 'Mortgage',
    mortgageProvider: 'ENBD',
    areaAvgPriceSqft: 1850,
    priceVsAreaAvg: 2,
  },
  {
    id: 'TXN-033',
    date: '2026-03-09',
    area: 'Business Bay',
    areaId: 'business-bay',
    building: 'Dubai Heights',
    unitNumber: 'AP-2208',
    propertyType: 'Apartment',
    bedrooms: 3,
    size: 2050,
    transactionValue: 4000000,
    priceSqft: 1951,
    transactionType: 'Sale',
    usageType: 'Residential',
    isOffPlan: false,
    registrationStatus: 'Registered',
    buyerNationality: 'Pakistani',
    paymentMethod: 'Mortgage',
    mortgageProvider: 'ADIB',
    areaAvgPriceSqft: 1850,
    priceVsAreaAvg: 5,
  },
  {
    id: 'TXN-034',
    date: '2026-03-06',
    area: 'Business Bay',
    areaId: 'business-bay',
    building: 'The Opus',
    unitNumber: 'AP-3305',
    propertyType: 'Apartment',
    bedrooms: 2,
    size: 1500,
    transactionValue: 3200000,
    priceSqft: 2133,
    transactionType: 'Mortgage',
    usageType: 'Residential',
    isOffPlan: false,
    registrationStatus: 'Registered',
    buyerNationality: 'Lebanese',
    paymentMethod: 'Mortgage',
    mortgageProvider: 'FAB',
    areaAvgPriceSqft: 1850,
    priceVsAreaAvg: 15,
  },
  {
    id: 'TXN-035',
    date: '2026-03-02',
    area: 'Business Bay',
    areaId: 'business-bay',
    building: 'Vida Residence',
    unitNumber: 'AP-4408',
    propertyType: 'Apartment',
    bedrooms: 3,
    size: 1980,
    transactionValue: 3900000,
    priceSqft: 1970,
    transactionType: 'Sale',
    usageType: 'Residential',
    isOffPlan: false,
    registrationStatus: 'Registered',
    buyerNationality: 'Indian',
    paymentMethod: 'Mortgage',
    mortgageProvider: 'ENBD',
    areaAvgPriceSqft: 1850,
    priceVsAreaAvg: 6,
  },

  // Dubai Hills Estate (7 txns)
  {
    id: 'TXN-036',
    date: '2026-03-22',
    area: 'Dubai Hills Estate',
    areaId: 'dubai-hills-estate',
    building: 'DAMAC Hills Villas',
    unitNumber: 'V-045',
    propertyType: 'Villa',
    bedrooms: 4,
    size: 4500,
    transactionValue: 12800000,
    priceSqft: 2844,
    transactionType: 'Sale',
    usageType: 'Residential',
    isOffPlan: false,
    registrationStatus: 'Registered',
    buyerNationality: 'Indian',
    paymentMethod: 'Mortgage',
    mortgageProvider: 'ADIB',
    areaAvgPriceSqft: 2450,
    priceVsAreaAvg: 16,
  },
  {
    id: 'TXN-037',
    date: '2026-03-20',
    area: 'Dubai Hills Estate',
    areaId: 'dubai-hills-estate',
    building: 'Sobha Hartland Greens',
    unitNumber: 'AP-2205',
    propertyType: 'Apartment',
    bedrooms: 3,
    size: 2200,
    transactionValue: 6200000,
    priceSqft: 2818,
    transactionType: 'Sale',
    usageType: 'Residential',
    isOffPlan: false,
    registrationStatus: 'Registered',
    buyerNationality: 'Pakistani',
    paymentMethod: 'Mortgage',
    mortgageProvider: 'FAB',
    areaAvgPriceSqft: 2450,
    priceVsAreaAvg: 15,
  },
  {
    id: 'TXN-038',
    date: '2026-03-18',
    area: 'Dubai Hills Estate',
    areaId: 'dubai-hills-estate',
    building: 'DAMAC Hills Villas',
    unitNumber: 'TH-089',
    propertyType: 'Townhouse',
    bedrooms: 3,
    size: 2800,
    transactionValue: 8500000,
    priceSqft: 3036,
    transactionType: 'Sale',
    usageType: 'Residential',
    isOffPlan: false,
    registrationStatus: 'Registered',
    buyerNationality: 'British',
    paymentMethod: 'Mortgage',
    mortgageProvider: 'ENBD',
    areaAvgPriceSqft: 2450,
    priceVsAreaAvg: 24,
  },
  {
    id: 'TXN-039',
    date: '2026-03-15',
    area: 'Dubai Hills Estate',
    areaId: 'dubai-hills-estate',
    building: 'Sobha Hartland Greens',
    unitNumber: 'V-128',
    propertyType: 'Villa',
    bedrooms: 5,
    size: 5200,
    transactionValue: 15800000,
    priceSqft: 3038,
    transactionType: 'Sale',
    usageType: 'Residential',
    isOffPlan: false,
    registrationStatus: 'Registered',
    buyerNationality: 'Emirati',
    paymentMethod: 'Cash',
    areaAvgPriceSqft: 2450,
    priceVsAreaAvg: 24,
  },
  {
    id: 'TXN-040',
    date: '2026-03-12',
    area: 'Dubai Hills Estate',
    areaId: 'dubai-hills-estate',
    building: 'DAMAC Hills Villas',
    unitNumber: 'AP-1805',
    propertyType: 'Apartment',
    bedrooms: 2,
    size: 1450,
    transactionValue: 3800000,
    priceSqft: 2621,
    transactionType: 'Sale',
    usageType: 'Residential',
    isOffPlan: false,
    registrationStatus: 'Registered',
    buyerNationality: 'Indian',
    paymentMethod: 'Mortgage',
    mortgageProvider: 'ADIB',
    areaAvgPriceSqft: 2450,
    priceVsAreaAvg: 7,
  },
  {
    id: 'TXN-041',
    date: '2026-03-08',
    area: 'Dubai Hills Estate',
    areaId: 'dubai-hills-estate',
    building: 'Sobha Hartland Greens',
    unitNumber: 'V-156',
    propertyType: 'Villa',
    bedrooms: 4,
    size: 4800,
    transactionValue: 13500000,
    priceSqft: 2813,
    transactionType: 'Sale',
    usageType: 'Residential',
    isOffPlan: false,
    registrationStatus: 'Registered',
    buyerNationality: 'Russian',
    paymentMethod: 'Cash',
    areaAvgPriceSqft: 2450,
    priceVsAreaAvg: 15,
  },
  {
    id: 'TXN-042',
    date: '2026-03-04',
    area: 'Dubai Hills Estate',
    areaId: 'dubai-hills-estate',
    building: 'DAMAC Hills Villas',
    unitNumber: 'V-067',
    propertyType: 'Villa',
    bedrooms: 5,
    size: 5400,
    transactionValue: 28000000,
    priceSqft: 5185,
    transactionType: 'Sale',
    usageType: 'Residential',
    isOffPlan: false,
    registrationStatus: 'Registered',
    buyerNationality: 'Chinese',
    paymentMethod: 'Cash',
    areaAvgPriceSqft: 2450,
    priceVsAreaAvg: 112,
  },

  // Emirates Hills (3 txns)
  {
    id: 'TXN-043',
    date: '2026-03-19',
    area: 'Emirates Hills',
    areaId: 'emirates-hills',
    building: 'District One Villas',
    unitNumber: 'V-001',
    propertyType: 'Villa',
    bedrooms: 6,
    size: 9800,
    transactionValue: 220000000,
    priceSqft: 22449,
    transactionType: 'Sale',
    usageType: 'Residential',
    isOffPlan: false,
    registrationStatus: 'Registered',
    buyerNationality: 'Saudi',
    paymentMethod: 'Cash',
    areaAvgPriceSqft: 4200,
    priceVsAreaAvg: 435,
  },
  {
    id: 'TXN-044',
    date: '2026-03-07',
    area: 'Emirates Hills',
    areaId: 'emirates-hills',
    building: 'Emirates Hills Villas',
    unitNumber: 'V-089',
    propertyType: 'Villa',
    bedrooms: 7,
    size: 11200,
    transactionValue: 185000000,
    priceSqft: 16518,
    transactionType: 'Sale',
    usageType: 'Residential',
    isOffPlan: false,
    registrationStatus: 'Registered',
    buyerNationality: 'British',
    paymentMethod: 'Cash',
    areaAvgPriceSqft: 4200,
    priceVsAreaAvg: 293,
  },
  {
    id: 'TXN-045',
    date: '2026-02-25',
    area: 'Emirates Hills',
    areaId: 'emirates-hills',
    building: 'District One Villas',
    unitNumber: 'V-015',
    propertyType: 'Villa',
    bedrooms: 5,
    size: 8500,
    transactionValue: 145000000,
    priceSqft: 17059,
    transactionType: 'Sale',
    usageType: 'Residential',
    isOffPlan: false,
    registrationStatus: 'Registered',
    buyerNationality: 'Russian',
    paymentMethod: 'Cash',
    areaAvgPriceSqft: 4200,
    priceVsAreaAvg: 306,
  },

  // DIFC (3 txns)
  {
    id: 'TXN-046',
    date: '2026-03-21',
    area: 'DIFC',
    areaId: 'difc',
    building: 'One Central DIFC',
    unitNumber: 'AP-4205',
    propertyType: 'Apartment',
    bedrooms: 2,
    size: 1600,
    transactionValue: 5600000,
    priceSqft: 3500,
    transactionType: 'Sale',
    usageType: 'Residential',
    isOffPlan: false,
    registrationStatus: 'Registered',
    buyerNationality: 'British',
    paymentMethod: 'Cash',
    areaAvgPriceSqft: 2650,
    priceVsAreaAvg: 32,
  },
  {
    id: 'TXN-047',
    date: '2026-03-10',
    area: 'DIFC',
    areaId: 'difc',
    building: 'One Central DIFC',
    unitNumber: 'AP-2102',
    propertyType: 'Apartment',
    bedrooms: 3,
    size: 2200,
    transactionValue: 8500000,
    priceSqft: 3864,
    transactionType: 'Sale',
    usageType: 'Residential',
    isOffPlan: false,
    registrationStatus: 'Registered',
    buyerNationality: 'French',
    paymentMethod: 'Mortgage',
    mortgageProvider: 'ENBD',
    areaAvgPriceSqft: 2650,
    priceVsAreaAvg: 46,
  },
  {
    id: 'TXN-048',
    date: '2026-03-01',
    area: 'DIFC',
    areaId: 'difc',
    building: 'One Central DIFC',
    unitNumber: 'AP-3508',
    propertyType: 'Apartment',
    bedrooms: 2,
    size: 1750,
    transactionValue: 6800000,
    priceSqft: 3886,
    transactionType: 'Sale',
    usageType: 'Residential',
    isOffPlan: false,
    registrationStatus: 'Registered',
    buyerNationality: 'German',
    paymentMethod: 'Cash',
    areaAvgPriceSqft: 2650,
    priceVsAreaAvg: 47,
  },

  // Dubai South (5 txns)
  {
    id: 'TXN-049',
    date: '2026-03-24',
    area: 'Dubai South',
    areaId: 'dubai-south',
    building: 'Serenia Residences',
    unitNumber: 'AP-1508',
    propertyType: 'Apartment',
    bedrooms: 2,
    size: 1100,
    transactionValue: 1200000,
    priceSqft: 1091,
    transactionType: 'Sale',
    usageType: 'Residential',
    isOffPlan: true,
    registrationStatus: 'Pending',
    buyerNationality: 'Indian',
    paymentMethod: 'Mortgage',
    mortgageProvider: 'FAB',
    areaAvgPriceSqft: 850,
    priceVsAreaAvg: 28,
  },
  {
    id: 'TXN-050',
    date: '2026-03-16',
    area: 'Dubai South',
    areaId: 'dubai-south',
    building: 'Serenia Residences',
    unitNumber: 'TH-045',
    propertyType: 'Townhouse',
    bedrooms: 3,
    size: 2100,
    transactionValue: 1900000,
    priceSqft: 905,
    transactionType: 'Sale',
    usageType: 'Residential',
    isOffPlan: true,
    registrationStatus: 'Pending',
    buyerNationality: 'Pakistani',
    paymentMethod: 'Mortgage',
    mortgageProvider: 'ADIB',
    areaAvgPriceSqft: 850,
    priceVsAreaAvg: 6,
  },
  {
    id: 'TXN-051',
    date: '2026-03-12',
    area: 'Dubai South',
    areaId: 'dubai-south',
    building: 'Serenia Residences',
    unitNumber: 'AP-2204',
    propertyType: 'Apartment',
    bedrooms: 1,
    size: 850,
    transactionValue: 750000,
    priceSqft: 882,
    transactionType: 'Sale',
    usageType: 'Residential',
    isOffPlan: true,
    registrationStatus: 'Pending',
    buyerNationality: 'Indian',
    paymentMethod: 'Mortgage',
    mortgageProvider: 'ENBD',
    areaAvgPriceSqft: 850,
    priceVsAreaAvg: 4,
  },
  {
    id: 'TXN-052',
    date: '2026-03-08',
    area: 'Dubai South',
    areaId: 'dubai-south',
    building: 'Serenia Residences',
    unitNumber: 'AP-3302',
    propertyType: 'Apartment',
    bedrooms: 2,
    size: 1350,
    transactionValue: 1400000,
    priceSqft: 1037,
    transactionType: 'Sale',
    usageType: 'Residential',
    isOffPlan: true,
    registrationStatus: 'Pending',
    buyerNationality: 'Filipino',
    paymentMethod: 'Mortgage',
    mortgageProvider: 'FAB',
    areaAvgPriceSqft: 850,
    priceVsAreaAvg: 22,
  },
  {
    id: 'TXN-053',
    date: '2026-02-28',
    area: 'Dubai South',
    areaId: 'dubai-south',
    building: 'Serenia Residences',
    unitNumber: 'TH-072',
    propertyType: 'Townhouse',
    bedrooms: 3,
    size: 2500,
    transactionValue: 2300000,
    priceSqft: 920,
    transactionType: 'Sale',
    usageType: 'Residential',
    isOffPlan: true,
    registrationStatus: 'Pending',
    buyerNationality: 'Indian',
    paymentMethod: 'Mortgage',
    mortgageProvider: 'ADIB',
    areaAvgPriceSqft: 850,
    priceVsAreaAvg: 8,
  },

  // JBR (3 txns)
  {
    id: 'TXN-054',
    date: '2026-03-23',
    area: 'JBR',
    areaId: 'jbr',
    building: 'Rimal JBR',
    unitNumber: 'AP-2808',
    propertyType: 'Apartment',
    bedrooms: 2,
    size: 1450,
    transactionValue: 4200000,
    priceSqft: 2897,
    transactionType: 'Sale',
    usageType: 'Residential',
    isOffPlan: false,
    registrationStatus: 'Registered',
    buyerNationality: 'Indian',
    paymentMethod: 'Mortgage',
    mortgageProvider: 'ENBD',
    areaAvgPriceSqft: 2350,
    priceVsAreaAvg: 23,
  },
  {
    id: 'TXN-055',
    date: '2026-03-13',
    area: 'JBR',
    areaId: 'jbr',
    building: 'Golden Crescent',
    unitNumber: 'AP-3505',
    propertyType: 'Apartment',
    bedrooms: 3,
    size: 1950,
    transactionValue: 5200000,
    priceSqft: 2667,
    transactionType: 'Sale',
    usageType: 'Residential',
    isOffPlan: false,
    registrationStatus: 'Registered',
    buyerNationality: 'British',
    paymentMethod: 'Mortgage',
    mortgageProvider: 'FAB',
    areaAvgPriceSqft: 2350,
    priceVsAreaAvg: 13,
  },
  {
    id: 'TXN-056',
    date: '2026-02-26',
    area: 'JBR',
    areaId: 'jbr',
    building: 'Rimal JBR',
    unitNumber: 'AP-1204',
    propertyType: 'Apartment',
    bedrooms: 2,
    size: 1350,
    transactionValue: 3500000,
    priceSqft: 2593,
    transactionType: 'Sale',
    usageType: 'Residential',
    isOffPlan: false,
    registrationStatus: 'Registered',
    buyerNationality: 'Pakistani',
    paymentMethod: 'Mortgage',
    mortgageProvider: 'ADIB',
    areaAvgPriceSqft: 2350,
    priceVsAreaAvg: 10,
  },

  // MBR City (3 txns)
  {
    id: 'TXN-057',
    date: '2026-03-20',
    area: 'MBR City',
    areaId: 'mbr-city',
    building: 'MBR City Residences',
    unitNumber: 'AP-2105',
    propertyType: 'Apartment',
    bedrooms: 2,
    size: 1400,
    transactionValue: 2800000,
    priceSqft: 2000,
    transactionType: 'Sale',
    usageType: 'Residential',
    isOffPlan: false,
    registrationStatus: 'Registered',
    buyerNationality: 'Indian',
    paymentMethod: 'Mortgage',
    mortgageProvider: 'ENBD',
    areaAvgPriceSqft: 1650,
    priceVsAreaAvg: 21,
  },
  {
    id: 'TXN-058',
    date: '2026-03-09',
    area: 'MBR City',
    areaId: 'mbr-city',
    building: 'Azizi Riviera',
    unitNumber: 'V-045',
    propertyType: 'Villa',
    bedrooms: 4,
    size: 4200,
    transactionValue: 12000000,
    priceSqft: 2857,
    transactionType: 'Sale',
    usageType: 'Residential',
    isOffPlan: false,
    registrationStatus: 'Registered',
    buyerNationality: 'Emirati',
    paymentMethod: 'Cash',
    areaAvgPriceSqft: 1650,
    priceVsAreaAvg: 73,
  },
  {
    id: 'TXN-059',
    date: '2026-03-05',
    area: 'MBR City',
    areaId: 'mbr-city',
    building: 'MBR City Residences',
    unitNumber: 'AP-4208',
    propertyType: 'Apartment',
    bedrooms: 3,
    size: 2100,
    transactionValue: 4200000,
    priceSqft: 2000,
    transactionType: 'Sale',
    usageType: 'Residential',
    isOffPlan: false,
    registrationStatus: 'Registered',
    buyerNationality: 'French',
    paymentMethod: 'Mortgage',
    mortgageProvider: 'FAB',
    areaAvgPriceSqft: 1650,
    priceVsAreaAvg: 21,
  },

  // Additional mixed transactions
  {
    id: 'TXN-060',
    date: '2026-02-24',
    area: 'Downtown Dubai',
    areaId: 'downtown-dubai',
    building: 'Address Downtown',
    unitNumber: 'AP-1809',
    propertyType: 'Apartment',
    bedrooms: 2,
    size: 1600,
    transactionValue: 5200000,
    priceSqft: 3250,
    transactionType: 'Gift',
    usageType: 'Residential',
    isOffPlan: false,
    registrationStatus: 'Registered',
    buyerNationality: 'Emirati',
    sellerNationality: 'Emirati',
    paymentMethod: 'Cash',
    areaAvgPriceSqft: 2800,
    priceVsAreaAvg: 16,
  },
]

// Volume by Month (Apr 2025 - Mar 2026)
const volumeByMonthData: VolumeByPeriod[] = [
  {
    period: '2025-04',
    transactions: 142,
    totalValue: 285600000,
    avgValue: 2011268,
    offPlanPct: 18,
    cashPct: 58,
  },
  {
    period: '2025-05',
    transactions: 128,
    totalValue: 267400000,
    avgValue: 2089063,
    offPlanPct: 22,
    cashPct: 56,
  },
  {
    period: '2025-06',
    transactions: 95,
    totalValue: 198500000,
    avgValue: 2089474,
    offPlanPct: 25,
    cashPct: 52,
  },
  {
    period: '2025-07',
    transactions: 82,
    totalValue: 175200000,
    avgValue: 2136585,
    offPlanPct: 28,
    cashPct: 50,
  },
  {
    period: '2025-08',
    transactions: 78,
    totalValue: 162400000,
    avgValue: 2082051,
    offPlanPct: 31,
    cashPct: 48,
  },
  {
    period: '2025-09',
    transactions: 88,
    totalValue: 186300000,
    avgValue: 2116477,
    offPlanPct: 29,
    cashPct: 51,
  },
  {
    period: '2025-10',
    transactions: 165,
    totalValue: 385600000,
    avgValue: 2336364,
    offPlanPct: 26,
    cashPct: 59,
  },
  {
    period: '2025-11',
    transactions: 178,
    totalValue: 425800000,
    avgValue: 2391573,
    offPlanPct: 24,
    cashPct: 62,
  },
  {
    period: '2025-12',
    transactions: 195,
    totalValue: 512400000,
    avgValue: 2627179,
    offPlanPct: 21,
    cashPct: 65,
  },
  {
    period: '2026-01',
    transactions: 188,
    totalValue: 485200000,
    avgValue: 2579787,
    offPlanPct: 19,
    cashPct: 63,
  },
  {
    period: '2026-02',
    transactions: 156,
    totalValue: 398600000,
    avgValue: 2553846,
    offPlanPct: 22,
    cashPct: 61,
  },
  {
    period: '2026-03',
    transactions: 92,
    totalValue: 282400000,
    avgValue: 3069565,
    offPlanPct: 28,
    cashPct: 58,
  },
]

// Volume by Area
const volumeByAreaData: VolumeByArea[] = [
  {
    area: 'Palm Jumeirah',
    areaId: 'palm-jumeirah',
    transactions: 142,
    totalValue: 585200000,
    avgPriceSqft: 3850,
    momChange: 12.5,
    yoyChange: 28.3,
  },
  {
    area: 'Dubai Marina',
    areaId: 'dubai-marina',
    transactions: 258,
    totalValue: 498900000,
    avgPriceSqft: 2150,
    momChange: -3.2,
    yoyChange: 15.8,
  },
  {
    area: 'Downtown Dubai',
    areaId: 'downtown-dubai',
    transactions: 195,
    totalValue: 612300000,
    avgPriceSqft: 2800,
    momChange: 8.4,
    yoyChange: 22.1,
  },
  {
    area: 'Business Bay',
    areaId: 'business-bay',
    transactions: 285,
    totalValue: 358200000,
    avgPriceSqft: 1850,
    momChange: -1.8,
    yoyChange: 11.2,
  },
  {
    area: 'Dubai Hills Estate',
    areaId: 'dubai-hills-estate',
    transactions: 168,
    totalValue: 425800000,
    avgPriceSqft: 2450,
    momChange: 5.6,
    yoyChange: 18.9,
  },
  {
    area: 'Emirates Hills',
    areaId: 'emirates-hills',
    transactions: 48,
    totalValue: 625400000,
    avgPriceSqft: 4200,
    momChange: 18.2,
    yoyChange: 35.7,
  },
  {
    area: 'DIFC',
    areaId: 'difc',
    transactions: 92,
    totalValue: 245600000,
    avgPriceSqft: 2650,
    momChange: 3.1,
    yoyChange: 12.4,
  },
  {
    area: 'Dubai South',
    areaId: 'dubai-south',
    transactions: 124,
    totalValue: 98200000,
    avgPriceSqft: 850,
    momChange: 22.5,
    yoyChange: 42.1,
  },
  {
    area: 'JBR',
    areaId: 'jbr',
    transactions: 156,
    totalValue: 268400000,
    avgPriceSqft: 2350,
    momChange: -2.3,
    yoyChange: 9.6,
  },
  {
    area: 'MBR City',
    areaId: 'mbr-city',
    transactions: 118,
    totalValue: 182600000,
    avgPriceSqft: 1650,
    momChange: 15.8,
    yoyChange: 31.4,
  },
]

// Volume by Property Type
const volumeByTypeData: VolumeByType[] = [
  {
    propertyType: 'Apartment',
    transactions: 1045,
    totalValue: 2245800000,
    avgValue: 2149426,
    pctOfTotal: 62.3,
  },
  {
    propertyType: 'Villa',
    transactions: 285,
    totalValue: 1125600000,
    avgValue: 3949123,
    pctOfTotal: 21.2,
  },
  {
    propertyType: 'Penthouse',
    transactions: 156,
    totalValue: 685400000,
    avgValue: 4393590,
    pctOfTotal: 10.5,
  },
  {
    propertyType: 'Townhouse',
    transactions: 82,
    totalValue: 158900000,
    avgValue: 1938415,
    pctOfTotal: 3.0,
  },
  {
    propertyType: 'Land',
    transactions: 28,
    totalValue: 125600000,
    avgValue: 4485714,
    pctOfTotal: 1.9,
  },
  {
    propertyType: 'Office',
    transactions: 32,
    totalValue: 198400000,
    avgValue: 6200000,
    pctOfTotal: 0.8,
  },
  {
    propertyType: 'Retail',
    transactions: 12,
    totalValue: 45200000,
    avgValue: 3766667,
    pctOfTotal: 0.3,
  },
]

// Buyer Profiles
const buyerProfilesData: BuyerProfile[] = [
  {
    nationality: 'Indian',
    transactionCount: 428,
    totalValue: 685200000,
    avgTransactionValue: 1601402,
    cashPct: 42,
    preferredAreas: ['Business Bay', 'Dubai Marina', 'JBR'],
    preferredTypes: ['Apartment', 'Townhouse'],
    goldenVisaEligiblePct: 8.2,
    trend: 'increasing',
    momChange: 8.5,
  },
  {
    nationality: 'British',
    transactionCount: 185,
    totalValue: 562400000,
    avgTransactionValue: 3040000,
    cashPct: 72,
    preferredAreas: ['Palm Jumeirah', 'Downtown Dubai', 'Emirates Hills'],
    preferredTypes: ['Penthouse', 'Villa'],
    goldenVisaEligiblePct: 45.9,
    trend: 'stable',
    momChange: 0.2,
  },
  {
    nationality: 'Russian',
    transactionCount: 168,
    totalValue: 624500000,
    avgTransactionValue: 3719345,
    cashPct: 78,
    preferredAreas: ['Palm Jumeirah', 'Emirates Hills', 'Downtown Dubai'],
    preferredTypes: ['Villa', 'Penthouse'],
    goldenVisaEligiblePct: 52.4,
    trend: 'stable',
    momChange: -1.2,
  },
  {
    nationality: 'Emirati',
    transactionCount: 142,
    totalValue: 485200000,
    avgTransactionValue: 3418310,
    cashPct: 88,
    preferredAreas: ['Palm Jumeirah', 'Emirates Hills', 'Dubai Hills Estate'],
    preferredTypes: ['Villa', 'Penthouse'],
    goldenVisaEligiblePct: 48.6,
    trend: 'increasing',
    momChange: 5.8,
  },
  {
    nationality: 'Chinese',
    transactionCount: 95,
    totalValue: 425800000,
    avgTransactionValue: 4482105,
    cashPct: 85,
    preferredAreas: ['Palm Jumeirah', 'Emirates Hills', 'Downtown Dubai'],
    preferredTypes: ['Villa', 'Apartment'],
    goldenVisaEligiblePct: 58.9,
    trend: 'increasing',
    momChange: 12.3,
  },
  {
    nationality: 'Pakistani',
    transactionCount: 82,
    totalValue: 168300000,
    avgTransactionValue: 2052439,
    cashPct: 35,
    preferredAreas: ['Business Bay', 'JBR', 'Dubai Hills Estate'],
    preferredTypes: ['Apartment', 'Townhouse'],
    goldenVisaEligiblePct: 6.1,
    trend: 'stable',
    momChange: 2.1,
  },
  {
    nationality: 'French',
    transactionCount: 48,
    totalValue: 185600000,
    avgTransactionValue: 3866667,
    cashPct: 65,
    preferredAreas: ['Palm Jumeirah', 'DIFC', 'Dubai Marina'],
    preferredTypes: ['Apartment', 'Penthouse'],
    goldenVisaEligiblePct: 35.4,
    trend: 'decreasing',
    momChange: -3.2,
  },
  {
    nationality: 'Saudi',
    transactionCount: 62,
    totalValue: 285400000,
    avgTransactionValue: 4600000,
    cashPct: 92,
    preferredAreas: ['Emirates Hills', 'Palm Jumeirah', 'Downtown Dubai'],
    preferredTypes: ['Villa', 'Penthouse'],
    goldenVisaEligiblePct: 72.6,
    trend: 'increasing',
    momChange: 9.5,
  },
  {
    nationality: 'German',
    transactionCount: 35,
    totalValue: 128400000,
    avgTransactionValue: 3668571,
    cashPct: 68,
    preferredAreas: ['DIFC', 'Downtown Dubai', 'Dubai Marina'],
    preferredTypes: ['Apartment', 'Penthouse'],
    goldenVisaEligiblePct: 31.4,
    trend: 'stable',
    momChange: 1.8,
  },
  {
    nationality: 'American',
    transactionCount: 28,
    totalValue: 95600000,
    avgTransactionValue: 3414286,
    cashPct: 71,
    preferredAreas: ['Palm Jumeirah', 'Downtown Dubai', 'DIFC'],
    preferredTypes: ['Apartment', 'Villa'],
    goldenVisaEligiblePct: 28.6,
    trend: 'decreasing',
    momChange: -2.1,
  },
]

// Building Analytics (10 iconic buildings)
const buildingAnalyticsData: BuildingAnalytics[] = [
  {
    building: 'Burj Khalifa',
    area: 'Downtown Dubai',
    areaId: 'downtown-dubai',
    totalTransactions: 38,
    avgPriceSqft: 5200,
    priceTrend: [4850, 4920, 5050, 5120, 5180, 5250, 5310, 5380, 5420, 5350, 5280, 5200],
    lastTransactionDate: '2026-03-24',
    lastTransactionPrice: 11200000,
    priceVsAreaAvg: 86,
    topBuyerNationalities: [
      { nationality: 'Russian', pct: 28 },
      { nationality: 'British', pct: 18 },
      { nationality: 'Saudi', pct: 16 },
    ],
    transactions: transactionsData.filter(t => t.building === 'Burj Khalifa'),
  },
  {
    building: 'Princess Tower',
    area: 'Dubai Marina',
    areaId: 'dubai-marina',
    totalTransactions: 56,
    avgPriceSqft: 3400,
    priceTrend: [3150, 3200, 3250, 3300, 3350, 3380, 3400, 3420, 3450, 3480, 3500, 3400],
    lastTransactionDate: '2026-03-23',
    lastTransactionPrice: 4500000,
    priceVsAreaAvg: 58,
    topBuyerNationalities: [
      { nationality: 'Indian', pct: 32 },
      { nationality: 'Pakistani', pct: 14 },
      { nationality: 'Russian', pct: 12 },
    ],
    transactions: transactionsData.filter(t => t.building === 'Princess Tower'),
  },
  {
    building: 'One at Palm Jumeirah',
    area: 'Palm Jumeirah',
    areaId: 'palm-jumeirah',
    totalTransactions: 34,
    avgPriceSqft: 12800,
    priceTrend: [11200, 11500, 11850, 12100, 12350, 12600, 12850, 13050, 13200, 13100, 12900, 12800],
    lastTransactionDate: '2026-03-22',
    lastTransactionPrice: 85000000,
    priceVsAreaAvg: 232,
    topBuyerNationalities: [
      { nationality: 'British', pct: 26 },
      { nationality: 'Chinese', pct: 20 },
      { nationality: 'Russian', pct: 18 },
    ],
    transactions: transactionsData.filter(t => t.building === 'One at Palm Jumeirah'),
  },
  {
    building: 'Address Downtown',
    area: 'Downtown Dubai',
    areaId: 'downtown-dubai',
    totalTransactions: 42,
    avgPriceSqft: 4850,
    priceTrend: [4520, 4580, 4650, 4720, 4800, 4850, 4900, 4950, 5000, 4950, 4900, 4850],
    lastTransactionDate: '2026-03-20',
    lastTransactionPrice: 38000000,
    priceVsAreaAvg: 73,
    topBuyerNationalities: [
      { nationality: 'Emirati', pct: 24 },
      { nationality: 'British', pct: 19 },
      { nationality: 'Chinese', pct: 16 },
    ],
    transactions: transactionsData.filter(t => t.building === 'Address Downtown'),
  },
  {
    building: 'Marina Gate',
    area: 'Dubai Marina',
    areaId: 'dubai-marina',
    totalTransactions: 48,
    avgPriceSqft: 5200,
    priceTrend: [4850, 4950, 5050, 5120, 5180, 5200, 5250, 5300, 5320, 5280, 5240, 5200],
    lastTransactionDate: '2026-03-21',
    lastTransactionPrice: 28000000,
    priceVsAreaAvg: 142,
    topBuyerNationalities: [
      { nationality: 'British', pct: 22 },
      { nationality: 'Russian', pct: 20 },
      { nationality: 'Lebanese', pct: 12 },
    ],
    transactions: transactionsData.filter(t => t.building === 'Marina Gate'),
  },
  {
    building: 'The Opus',
    area: 'Business Bay',
    areaId: 'business-bay',
    totalTransactions: 52,
    avgPriceSqft: 2280,
    priceTrend: [2050, 2100, 2150, 2180, 2220, 2250, 2270, 2280, 2300, 2310, 2300, 2280],
    lastTransactionDate: '2026-03-23',
    lastTransactionPrice: 2800000,
    priceVsAreaAvg: 23,
    topBuyerNationalities: [
      { nationality: 'Indian', pct: 38 },
      { nationality: 'British', pct: 16 },
      { nationality: 'Pakistani', pct: 11 },
    ],
    transactions: transactionsData.filter(t => t.building === 'The Opus'),
  },
  {
    building: 'DAMAC Hills Villas',
    area: 'Dubai Hills Estate',
    areaId: 'dubai-hills-estate',
    totalTransactions: 64,
    avgPriceSqft: 2950,
    priceTrend: [2620, 2680, 2750, 2820, 2880, 2920, 2950, 2980, 3000, 2980, 2960, 2950],
    lastTransactionDate: '2026-03-22',
    lastTransactionPrice: 12800000,
    priceVsAreaAvg: 20,
    topBuyerNationalities: [
      { nationality: 'Indian', pct: 28 },
      { nationality: 'Emirati', pct: 18 },
      { nationality: 'Russian', pct: 14 },
    ],
    transactions: transactionsData.filter(t => t.building === 'DAMAC Hills Villas'),
  },
  {
    building: 'Rimal JBR',
    area: 'JBR',
    areaId: 'jbr',
    totalTransactions: 58,
    avgPriceSqft: 2680,
    priceTrend: [2450, 2500, 2550, 2600, 2640, 2670, 2680, 2700, 2720, 2700, 2690, 2680],
    lastTransactionDate: '2026-03-23',
    lastTransactionPrice: 4200000,
    priceVsAreaAvg: 14,
    topBuyerNationalities: [
      { nationality: 'Indian', pct: 35 },
      { nationality: 'Filipino', pct: 12 },
      { nationality: 'British', pct: 11 },
    ],
    transactions: transactionsData.filter(t => t.building === 'Rimal JBR'),
  },
  {
    building: 'Atlantis The Royal Residences',
    area: 'Palm Jumeirah',
    areaId: 'palm-jumeirah',
    totalTransactions: 28,
    avgPriceSqft: 9500,
    priceTrend: [8850, 9050, 9200, 9350, 9450, 9520, 9580, 9620, 9650, 9580, 9540, 9500],
    lastTransactionDate: '2026-03-20',
    lastTransactionPrice: 18500000,
    priceVsAreaAvg: 147,
    topBuyerNationalities: [
      { nationality: 'Russian', pct: 32 },
      { nationality: 'Saudi', pct: 18 },
      { nationality: 'Emirati', pct: 14 },
    ],
    transactions: transactionsData.filter(t => t.building === 'Atlantis The Royal Residences'),
  },
  {
    building: 'District One Villas',
    area: 'Emirates Hills',
    areaId: 'emirates-hills',
    totalTransactions: 16,
    avgPriceSqft: 19800,
    priceTrend: [17200, 17800, 18400, 18900, 19300, 19600, 19800, 20000, 20150, 20050, 19950, 19800],
    lastTransactionDate: '2026-03-19',
    lastTransactionPrice: 220000000,
    priceVsAreaAvg: 371,
    topBuyerNationalities: [
      { nationality: 'Saudi', pct: 38 },
      { nationality: 'British', pct: 19 },
      { nationality: 'Russian', pct: 19 },
    ],
    transactions: transactionsData.filter(t => t.building === 'District One Villas'),
  },
]

// Transaction Summary
const summaryData: TransactionSummary = {
  totalTransactions: 1726,
  totalValue: 6585400000,
  avgTransactionValue: 3813854,
  avgPriceSqft: 2456,
  offPlanPct: 24,
  cashPct: 59,
  topArea: 'Downtown Dubai',
  topNationality: 'Indian',
  momVolumeChange: 8.2,
  yoyVolumeChange: 19.5,
}

// ===================== REAL DLD DATA (Q1 2026) =====================
// Imported from processed dubailand.gov.ae open data export
import {
  REAL_TRANSACTION_SUMMARY,
  REAL_VOLUME_BY_MONTH,
  REAL_VOLUME_BY_AREA,
  REAL_VOLUME_BY_TYPE,
  REAL_RECENT_TRANSACTIONS,
  REAL_TOP_TRANSACTIONS,
  REAL_BUILDING_ANALYTICS,
  REAL_DATA_META,
} from './realTransactionData'

// Use real DLD data as primary source, keep mock as fallback
const USE_REAL_DATA = true

const activeTransactions = USE_REAL_DATA ? REAL_RECENT_TRANSACTIONS : transactionsData
const activeVolumeByMonth = USE_REAL_DATA ? REAL_VOLUME_BY_MONTH : volumeByMonthData
const activeVolumeByArea = USE_REAL_DATA ? REAL_VOLUME_BY_AREA : volumeByAreaData
const activeVolumeByType = USE_REAL_DATA ? REAL_VOLUME_BY_TYPE : volumeByTypeData
const activeBuildingAnalytics = USE_REAL_DATA ? REAL_BUILDING_ANALYTICS : buildingAnalyticsData
const activeSummary = USE_REAL_DATA ? REAL_TRANSACTION_SUMMARY : summaryData

// ===================== EXPORT DATA =====================

export const mockTransactionData = {
  transactions: activeTransactions,
  volumeByMonth: activeVolumeByMonth,
  volumeByArea: activeVolumeByArea,
  volumeByType: activeVolumeByType,
  buyerProfiles: buyerProfilesData,
  buildingAnalytics: activeBuildingAnalytics,
  summary: activeSummary,
}

export { REAL_DATA_META }

// ===================== HELPER FUNCTIONS =====================

export function getTransaction(id: string): Transaction | undefined {
  return activeTransactions.find(t => t.id === id)
}

export function getTransactionsByArea(areaId: string): Transaction[] {
  return activeTransactions.filter(t => t.areaId === areaId)
}

export function getTransactionsByBuilding(building: string): Transaction[] {
  return activeTransactions.filter(t => t.building === building)
}

export function getTransactionsByNationality(nationality: string): Transaction[] {
  return activeTransactions.filter(t => t.buyerNationality === nationality)
}

export function getTopTransactions(count: number, days: number): Transaction[] {
  const cutoffDate = new Date('2026-03-26')
  cutoffDate.setDate(cutoffDate.getDate() - days)

  return (USE_REAL_DATA ? REAL_TOP_TRANSACTIONS : activeTransactions)
    .filter(t => new Date(t.date) >= cutoffDate)
    .sort((a, b) => b.transactionValue - a.transactionValue)
    .slice(0, count)
}

export function getBuildingAnalytics(building: string): BuildingAnalytics | undefined {
  return activeBuildingAnalytics.find(b => b.building === building)
}
