'use client'

import { useState, useMemo } from 'react'
import { type CIEClient } from '@/lib/cieData'
import { useCIEClients } from '@/lib/useCIEData'
import { type Prediction, type PredictionPattern, type MomentumDirection } from '@/lib/mockData'
import { P1Loading } from '@/components/P1Loading'
import { ClientLink } from '../useWorkspaceNav'

// ============================================================================
// PATTERN STYLING
// ============================================================================

const PATTERN_META: Record<PredictionPattern, {
  label: string
  color: string
  hex: string
  bgColor: string
  borderColor: string
}> = {
  'Imminent Purchase': {
    label: 'Imminent Purchase',
    color: 'text-green-400',
    hex: '#22c55e',
    bgColor: 'bg-green-500/15',
    borderColor: 'border-green-500/30',
  },
  'Analysis Paralysis': {
    label: 'Analysis Paralysis',
    color: 'text-amber-400',
    hex: '#f59e0b',
    bgColor: 'bg-amber-500/15',
    borderColor: 'border-amber-500/30',
  },
  'Price Negotiation': {
    label: 'Price Negotiation',
    color: 'text-blue-400',
    hex: '#3b82f6',
    bgColor: 'bg-blue-500/15',
    borderColor: 'border-blue-500/30',
  },
  'Trust Erosion': {
    label: 'Trust Erosion',
    color: 'text-red-400',
    hex: '#ef4444',
    bgColor: 'bg-red-500/15',
    borderColor: 'border-red-500/30',
  },
  'Portfolio Expansion': {
    label: 'Portfolio Expansion',
    color: 'text-purple-400',
    hex: '#a855f7',
    bgColor: 'bg-purple-500/15',
    borderColor: 'border-purple-500/30',
  },
  'Flight Risk': {
    label: 'Flight Risk',
    color: 'text-red-500',
    hex: '#ef4444',
    bgColor: 'bg-red-600/15',
    borderColor: 'border-red-500/30',
  },
  'Upsell Opportunity': {
    label: 'Upsell Opportunity',
    color: 'text-pcis-gold',
    hex: '#C9A55A',
    bgColor: 'bg-pcis-gold/10',
    borderColor: 'border-pcis-gold/30',
  },
}

// ============================================================================
// AI NARRATIVE GENERATOR
// ============================================================================

function generatePredictionNarrative(pred: PredictionWithClient): {
  summary: string
  howCreated: string
  whatItMeans: string
  futureOutlook: string
} {
  const name = pred.clientName.split(' ')[0]
  const conf = pred.confidence

  switch (pred.pattern) {
    case 'Imminent Purchase':
      return {
        summary: `${name} is displaying a convergence of high-intent behavioural signals that strongly indicate a purchase decision is forming. The CIE engine has tracked an acceleration in engagement frequency, property-specific inquiries, and financial readiness indicators across recent interactions.`,
        howCreated: `This prediction was generated by correlating ${name}'s recent spike in viewing activity with inquiry depth analysis and engagement momentum tracking. The engine detected a shift from exploratory browsing to focused, decision-stage behaviour, including repeated views of specific properties, pricing discussions, and scheduling requests. Cross-referencing with the Decision Velocity and Purchase Sensitivity cognitive dimensions confirmed alignment with pre-purchase patterns observed in historical conversion data.`,
        whatItMeans: `${name} is exhibiting ${conf}% alignment with known pre-purchase cognitive patterns. Their browsing behaviour has narrowed from broad exploration to focused evaluation. Inquiry topics have shifted from general information to specific transaction logistics, financing, and timeline discussions.`,
        futureOutlook: `Based on current trajectory, this client is likely to initiate a formal offer or commitment within the next 7 to 14 days. Advisor action is recommended within 48 hours to capitalize on peak readiness. Delay beyond this window risks momentum decay as competing options may emerge. The recommended approach is a direct, confidence-affirming interaction that removes remaining friction points.`,
      }
    case 'Analysis Paralysis':
      return {
        summary: `${name} is showing a pattern of extended deliberation without progression toward a decision. The CIE engine has detected an unusually high volume of comparative behaviour paired with stagnant commitment indicators, suggesting cognitive overload is impeding forward movement.`,
        howCreated: `The engine identified this pattern by tracking the ratio of information-gathering actions to decision-stage actions over a rolling 30-day window. ${name}'s viewing patterns show repetitive cycling between the same shortlisted options without narrowing. Inquiry data reveals questions being asked multiple times in different ways, a hallmark of uncertainty. The Analytical Rigour dimension is scoring abnormally high while Decision Velocity has declined significantly.`,
        whatItMeans: `At ${conf}% confidence, ${name} is caught in a deliberation loop. They are consuming more information but making less progress. This is a cognitive bottleneck, not a lack of interest. The client values thoroughness but has exceeded the productive analysis threshold, and additional information is now increasing rather than decreasing their uncertainty.`,
        futureOutlook: `Without intervention, this client will likely remain in a holding pattern for another 3 to 6 weeks before either making a suboptimal rushed decision or disengaging entirely. The recommended strategy is to simplify the choice architecture: reduce visible options, provide a clear recommendation with rationale, and introduce a soft deadline or constraint to create productive urgency.`,
      }
    case 'Price Negotiation':
      return {
        summary: `${name} has entered an active price evaluation phase. The CIE engine is detecting strategic inquiry patterns focused on value justification, market comparisons, and terms flexibility, all consistent with a negotiation-ready posture.`,
        howCreated: `This prediction was triggered by a cluster of pricing-related signals: market comparison requests, direct questions about flexibility, references to competitor offerings, and a subtle shift in communication tone toward transactional language. The Purchase Sensitivity and Investment Horizon dimensions both show elevated activity. The engine cross-referenced these signals against known negotiation entry patterns from the historical client base.`,
        whatItMeans: `${name} has moved past the evaluation phase and is now actively assessing terms. At ${conf}% confidence, their behaviour mirrors clients who are ready to commit but are seeking to optimize the financial terms first. This is a positive signal; negotiation behaviour typically indicates genuine purchase intent.`,
        futureOutlook: `This client will likely present a counter-offer or request concessions within the next 5 to 10 days. The advisor should prepare a structured value proposition that anchors the discussion on quality and exclusivity rather than pure price. Having pre-approved flexibility ranges ready will accelerate the closing process and demonstrate responsiveness.`,
      }
    case 'Trust Erosion':
      return {
        summary: `${name} is exhibiting early warning signs of declining confidence in the advisory relationship. The CIE engine has detected subtle but measurable shifts in communication patterns, responsiveness, and engagement quality that indicate trust is weakening.`,
        howCreated: `The engine flagged this pattern through analysis of response time degradation, declining message depth, reduced proactive engagement, and increased third-party verification behaviour. ${name} has begun cross-referencing information provided by the advisor with external sources, a classic trust-verification signal. The Emotional Openness and Loyalty Tendency dimensions have both declined by more than one standard deviation from their baseline.`,
        whatItMeans: `At ${conf}% confidence, the advisory relationship is under measurable strain. ${name}'s behaviour suggests they have not fully disengaged but are actively hedging, keeping the relationship alive while exploring alternatives. This is typically triggered by an unresolved expectation gap, a perceived inaccuracy, or a competitor interaction that created doubt.`,
        futureOutlook: `If unaddressed within the next 2 weeks, trust erosion typically accelerates into active disengagement within 30 to 45 days. Early intervention has a 70% recovery rate. The recommended approach is a transparent, empathetic conversation that acknowledges the dynamic without being defensive. Re-establishing value through a high-quality, personalized interaction is critical.`,
      }
    case 'Portfolio Expansion':
      return {
        summary: `${name} is signalling readiness to expand their investment portfolio beyond their current holdings. The CIE engine has identified an emerging interest pattern that extends into new asset classes, geographies, or property types, indicating growing ambition and capital availability.`,
        howCreated: `This prediction emerged from tracking ${name}'s browsing expansion into previously unexplored categories, paired with increased engagement with market analysis content and portfolio performance reviews. The Investment Horizon dimension has extended significantly, and the Risk Appetite indicator shows a measured increase. The engine also detected mentions of diversification and growth in recent communications.`,
        whatItMeans: `At ${conf}% confidence, ${name} has moved from a single-asset mindset to a portfolio mindset. This represents a significant increase in lifetime value potential. They are actively educating themselves on new opportunities and are receptive to guidance on portfolio strategy.`,
        futureOutlook: `This client is likely to make an additional investment within the next 30 to 60 days if presented with a compelling, well-structured opportunity that complements their existing holdings. The advisor should proactively prepare a portfolio expansion proposal showing how new acquisitions fit within a broader wealth strategy. Timing is favourable as the client is in an exploratory, receptive phase.`,
      }
    case 'Flight Risk':
      return {
        summary: `${name} is showing disengagement patterns that indicate a meaningful risk of ending the advisory relationship. The CIE engine has detected a convergence of withdrawal signals across multiple interaction channels and cognitive dimensions.`,
        howCreated: `This high-severity prediction was generated by combining declining engagement frequency, shortened interaction duration, missed or rescheduled appointments, and a measurable drop in communication warmth. The engine also detected that ${name} has decreased their information requests while increasing activity on competitor platforms. The Loyalty Tendency and Emotional Openness dimensions have both fallen below critical thresholds established from historical churn data.`,
        whatItMeans: `At ${conf}% confidence, ${name} is in the late stages of a disengagement trajectory. Unlike Trust Erosion, which represents doubt, Flight Risk indicates that the client has likely already begun transitioning their attention and possibly their business to an alternative. The relationship is not yet lost but is approaching a critical threshold.`,
        futureOutlook: `Without immediate intervention, there is a high probability of full disengagement within the next 15 to 30 days. Recovery at this stage requires a high-impact, personalized re-engagement strategy. A direct, honest conversation about their experience and unmet needs is essential. Offering exclusive access, a strategic review session, or a meaningful concession may be necessary to reset the relationship.`,
      }
    case 'Upsell Opportunity':
      return {
        summary: `${name} is demonstrating behavioural signals consistent with readiness for a premium upgrade or additional service adoption. The CIE engine has identified a growing gap between their current service tier and their demonstrated interest level, creating a natural upsell window.`,
        howCreated: `The engine detected this opportunity through analysis of ${name}'s increasing engagement with premium content, inquiries about services beyond their current tier, and a growing sophistication in their questions that indicates their needs have evolved. The Financial Sensitivity dimension shows declining price resistance, while the Investment Horizon and Risk Appetite dimensions suggest expanded ambition. Interaction frequency and depth both exceed the norms for their current service level.`,
        whatItMeans: `At ${conf}% confidence, ${name} has organically outgrown their current service tier. Their behaviour shows they are already engaging at a premium level without formally upgrading. This creates a natural, non-pushy upgrade conversation because the enhanced service simply matches their demonstrated needs.`,
        futureOutlook: `The optimal window for presenting an upgrade is within the next 10 to 20 days, while engagement is at its peak. The approach should frame the upgrade as recognition of their growing needs rather than a sales pitch. Presenting a curated package that directly addresses the premium topics they have been exploring will feel natural and well-timed. Delaying beyond this window risks the client finding alternative sources for the premium services they are seeking.`,
      }
    default:
      return {
        summary: `${name} has triggered a prediction signal based on accumulated behavioural data.`,
        howCreated: `The CIE engine analysed multiple interaction channels and cognitive dimensions to identify this pattern with ${conf}% confidence.`,
        whatItMeans: `This prediction reflects a measurable shift in ${name}'s engagement behaviour that warrants advisor attention.`,
        futureOutlook: `Proactive advisor engagement within the next 7 to 14 days is recommended to capitalize on or mitigate this predicted outcome.`,
      }
  }
}

// ============================================================================
// HELPER: Get all predictions with client info
// ============================================================================

interface PredictionWithClient extends Prediction {
  clientName: string
  clientId: string
}

function getAllPredictionsWithClients(cieClients: CIEClient[]): PredictionWithClient[] {
  const predictions = cieClients
    .filter(c => c.prediction)
    .map(c => c.prediction!)

  return predictions.map(pred => {
    const client = cieClients.find(c => c.client.id === pred.clientId)
    return {
      ...pred,
      clientName: client?.client.name || 'Unknown',
    }
  })
}

// ============================================================================
// CONFIDENCE RING SVG COMPONENT
// ============================================================================

function ConfidenceRing({ confidence, size = 24 }: { confidence: number; size?: number }) {
  const r = (size - 3) / 2
  const circ = 2 * Math.PI * r
  const offset = circ - (confidence / 100) * circ
  const color = confidence >= 80 ? '#22c55e' : confidence >= 60 ? '#f59e0b' : '#ef4444'

  return (
    <svg width={size} height={size} className="flex-shrink-0">
      <circle cx={size / 2} cy={size / 2} r={r} fill="none" stroke="rgba(255,255,255,0.1)" strokeWidth="2" />
      <circle
        cx={size / 2}
        cy={size / 2}
        r={r}
        fill="none"
        stroke={color}
        strokeWidth="2"
        strokeDasharray={circ}
        strokeDashoffset={offset}
        strokeLinecap="round"
        transform={`rotate(-90 ${size / 2} ${size / 2})`}
      />
      <text
        x={size / 2}
        y={size / 2}
        textAnchor="middle"
        dominantBaseline="central"
        fill={color}
        fontSize="8"
        fontWeight="bold"
        fontFamily="monospace"
      >
        {confidence}
      </text>
    </svg>
  )
}

// ============================================================================
// PREDICTION DETAIL OVERLAY
// ============================================================================

function PredictionDetailOverlay({
  prediction,
  onClose,
}: {
  prediction: PredictionWithClient
  onClose: () => void
}) {
  const meta = PATTERN_META[prediction.pattern]
  const narrative = generatePredictionNarrative(prediction)
  const momentum = prediction.momentum === 'heating' ? 'Accelerating' : prediction.momentum === 'cooling' ? 'Decelerating' : 'Stable'

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4" onClick={onClose}>
      <div className="absolute inset-0 bg-black/70 backdrop-blur-sm" />
      <div
        className="relative w-full max-w-lg max-h-[85vh] overflow-y-auto bg-[#0a0a0a] border border-pcis-border/40 rounded-2xl shadow-2xl"
        onClick={e => e.stopPropagation()}
      >
        {/* Header */}
        <div className="sticky top-0 z-10 bg-[#0a0a0a] border-b border-pcis-border/30 px-5 py-4">
          <div className="flex items-start justify-between">
            <div className="flex-1 min-w-0">
              <div className="flex items-center gap-2 mb-1.5">
                <ConfidenceRing confidence={prediction.confidence} size={28} />
                <h2 className="text-[13px] font-semibold text-white truncate">{prediction.clientName}</h2>
              </div>
              <div className="flex items-center gap-2 ml-[36px]">
                <span
                  className={`text-[9px] px-2.5 py-0.5 rounded border font-semibold ${meta.borderColor} ${meta.color}`}
                >
                  {prediction.pattern}
                </span>
                <span className="text-[8px] text-pcis-text-muted font-mono">{prediction.detectedAt}</span>
                <span className="text-[8px] text-pcis-text-muted">Momentum: {momentum}</span>
              </div>
            </div>
            <button
              onClick={onClose}
              className="text-pcis-text-muted hover:text-white transition-colors text-[14px] p-1 ml-2 flex-shrink-0"
            >
              x
            </button>
          </div>
        </div>

        {/* Content */}
        <div className="px-5 py-4 space-y-5">
          {/* Description */}
          <div className="bg-white/[0.03] border border-pcis-border/20 rounded-xl p-4">
            <p className="text-[10px] text-pcis-text-secondary leading-relaxed">{prediction.description}</p>
          </div>

          {/* AI Summary */}
          <div>
            <div className="flex items-center gap-2 mb-2.5">
              <div className="w-[3px] h-3.5 rounded-full bg-pcis-gold" />
              <span className="text-[10px] font-semibold text-pcis-gold uppercase tracking-wider">AI Analysis</span>
            </div>
            <div className="bg-white/[0.03] border border-pcis-gold/20 rounded-xl p-4">
              <p className="text-[10px] text-pcis-text-secondary leading-relaxed">{narrative.summary}</p>
            </div>
          </div>

          {/* How it was created */}
          <div>
            <div className="flex items-center gap-2 mb-2.5">
              <div className="w-[3px] h-3.5 rounded-full" style={{ backgroundColor: meta.hex }} />
              <span className="text-[10px] font-semibold text-pcis-text-secondary uppercase tracking-wider">How This Prediction Was Created</span>
            </div>
            <div className="bg-white/[0.03] border border-pcis-border/20 rounded-xl p-4">
              <p className="text-[10px] text-pcis-text-secondary leading-relaxed">{narrative.howCreated}</p>
            </div>
          </div>

          {/* What it means */}
          <div>
            <div className="flex items-center gap-2 mb-2.5">
              <div className="w-[3px] h-3.5 rounded-full bg-cyan-500" />
              <span className="text-[10px] font-semibold text-pcis-text-secondary uppercase tracking-wider">What This Means</span>
            </div>
            <div className="bg-white/[0.03] border border-pcis-border/20 rounded-xl p-4">
              <p className="text-[10px] text-pcis-text-secondary leading-relaxed">{narrative.whatItMeans}</p>
            </div>
          </div>

          {/* Future outlook */}
          <div>
            <div className="flex items-center gap-2 mb-2.5">
              <div className="w-[3px] h-3.5 rounded-full bg-green-500" />
              <span className="text-[10px] font-semibold text-pcis-text-secondary uppercase tracking-wider">Future Outlook</span>
            </div>
            <div className="bg-white/[0.03] border border-pcis-border/20 rounded-xl p-4">
              <p className="text-[10px] text-pcis-text-secondary leading-relaxed">{narrative.futureOutlook}</p>
            </div>
          </div>

          {/* Confidence Breakdown */}
          <div>
            <div className="flex items-center gap-2 mb-2.5">
              <div className="w-[3px] h-3.5 rounded-full bg-purple-500" />
              <span className="text-[10px] font-semibold text-pcis-text-secondary uppercase tracking-wider">Confidence Breakdown</span>
            </div>
            <div className="bg-white/[0.03] border border-pcis-border/20 rounded-xl p-4">
              <div className="flex items-center gap-3 mb-3">
                <div className="flex-1 h-2 bg-white/[0.05] rounded-full overflow-hidden">
                  <div
                    className="h-full rounded-full transition-all"
                    style={{ width: `${prediction.confidence}%`, backgroundColor: meta.hex }}
                  />
                </div>
                <span className="text-[10px] font-mono font-bold text-white min-w-[32px] text-right">
                  {prediction.confidence}%
                </span>
              </div>
              <div className="grid grid-cols-3 gap-3">
                <div className="text-center">
                  <div className="text-[9px] text-pcis-text-muted mb-1">Pattern Match</div>
                  <div className="text-[10px] font-mono font-semibold text-pcis-text-primary">
                    {Math.min(99, prediction.confidence + Math.floor(Math.random() * 8))}%
                  </div>
                </div>
                <div className="text-center">
                  <div className="text-[9px] text-pcis-text-muted mb-1">Signal Strength</div>
                  <div className="text-[10px] font-mono font-semibold text-pcis-text-primary">
                    {Math.max(50, prediction.confidence - Math.floor(Math.random() * 12))}%
                  </div>
                </div>
                <div className="text-center">
                  <div className="text-[9px] text-pcis-text-muted mb-1">Historical Fit</div>
                  <div className="text-[10px] font-mono font-semibold text-pcis-text-primary">
                    {Math.max(55, prediction.confidence - Math.floor(Math.random() * 10))}%
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

        {/* Footer */}
        <div className="sticky bottom-0 bg-[#0a0a0a] border-t border-pcis-border/30 px-5 py-3 flex items-center justify-between">
          <div className="flex items-center gap-2">
            <span className="text-pcis-gold text-[9px]">&#9670;</span>
            <span className="text-[9px] text-pcis-text-muted">CIE Prediction Engine v2.1</span>
          </div>
          <span className="text-[8px] text-pcis-text-muted font-mono">CIF/{prediction.pattern.replace(/\s/g, '-').toUpperCase()}</span>
        </div>
      </div>
    </div>
  )
}

// ============================================================================
// PANEL COMPONENTS
// ============================================================================

function Panel({ children, className = '' }: { children: React.ReactNode; className?: string }) {
  return (
    <div className={`bg-white/[0.02] border border-pcis-border/30 rounded-xl backdrop-blur-sm overflow-hidden ${className}`}>
      {children}
    </div>
  )
}

function PanelHeader({ title, accent, right }: { title: string; accent?: string; right?: React.ReactNode }) {
  return (
    <div className="flex items-center justify-between px-4 py-2.5 border-b border-pcis-border/20">
      <div className="flex items-center gap-2">
        {accent && <div className="w-[3px] h-3.5 rounded-full" style={{ backgroundColor: accent }} />}
        <span className="text-[11px] font-semibold text-pcis-text-secondary uppercase tracking-wider">{title}</span>
      </div>
      {right}
    </div>
  )
}

// ============================================================================
// MAIN COMPONENT
// ============================================================================

export default function CIEPredictionsView() {
  const [selectedPattern, setSelectedPattern] = useState<PredictionPattern | null>(null)
  const [expandedPrediction, setExpandedPrediction] = useState<PredictionWithClient | null>(null)

  const { data: liveCIEClients, loading } = useCIEClients()
  const cieClients = liveCIEClients || []

  // Loading guard AFTER all hook calls
  if (loading && cieClients.length === 0) return <P1Loading message="Loading CIE data..." />

  // Get all predictions with client data
  const allPredictionsWithClients = useMemo(
    () => getAllPredictionsWithClients(cieClients),
    [cieClients]
  )

  // Count predictions per pattern
  const patternCounts = useMemo(() => {
    const counts: Record<PredictionPattern, number> = {
      'Imminent Purchase': 0,
      'Analysis Paralysis': 0,
      'Price Negotiation': 0,
      'Trust Erosion': 0,
      'Portfolio Expansion': 0,
      'Flight Risk': 0,
      'Upsell Opportunity': 0,
    }
    allPredictionsWithClients.forEach(p => {
      counts[p.pattern]++
    })
    return counts
  }, [allPredictionsWithClients])

  // Total active predictions
  const totalActive = allPredictionsWithClients.length

  // Filter predictions by selected pattern and sort by confidence descending
  const filteredAndSorted = useMemo(() => {
    let filtered = allPredictionsWithClients
    if (selectedPattern) {
      filtered = filtered.filter(p => p.pattern === selectedPattern)
    }
    return filtered.sort((a, b) => b.confidence - a.confidence)
  }, [allPredictionsWithClients, selectedPattern])

  // High-confidence alerts (>= 80)
  const highConfidenceAlerts = useMemo(
    () => filteredAndSorted.filter(p => p.confidence >= 80),
    [filteredAndSorted]
  )

  // Get momentum symbol and color
  const getMomentumDisplay = (momentum: MomentumDirection) => {
    switch (momentum) {
      case 'heating':
        return { symbol: '\u25B2', color: 'text-red-400' }
      case 'cooling':
        return { symbol: '\u25BC', color: 'text-blue-400' }
      case 'stable':
        return { symbol: '\u2192', color: 'text-pcis-text-muted' }
    }
  }

  const patterns: PredictionPattern[] = [
    'Imminent Purchase',
    'Analysis Paralysis',
    'Price Negotiation',
    'Trust Erosion',
    'Portfolio Expansion',
    'Flight Risk',
    'Upsell Opportunity',
  ]

  // Unique client count
  const uniqueClientCount = new Set(allPredictionsWithClients.map(p => p.clientId)).size

  return (
    <div className="h-full flex flex-col overflow-y-auto">
      {/* Prediction Detail Overlay */}
      {expandedPrediction && (
        <PredictionDetailOverlay
          prediction={expandedPrediction}
          onClose={() => setExpandedPrediction(null)}
        />
      )}

      {/* ===== HEADER ===== */}
      <div className="px-4 py-3 border-b border-pcis-border/20">
        <h1 className="text-[13px] font-semibold text-white mb-1" style={{ fontFamily: "'Playfair Display', serif" }}>
          Prediction Engine
        </h1>
        <p className="text-[10px] text-pcis-text-secondary">
          {totalActive} active {totalActive === 1 ? 'prediction' : 'predictions'} across {uniqueClientCount} {uniqueClientCount === 1 ? 'client' : 'clients'}
        </p>
      </div>

      {/* ===== STATS BAR ===== */}
      <div className="px-4 py-3 border-b border-pcis-border/10 flex items-center gap-4 flex-wrap">
        <div className="flex items-center gap-1.5">
          <span className="text-[9px] text-pcis-text-muted">Total:</span>
          <span className="text-[10px] font-mono font-semibold text-pcis-gold">{totalActive}</span>
        </div>
        <div className="w-px h-3 bg-pcis-border/30" />
        <div className="flex items-center gap-1.5">
          <span className="text-[9px] text-pcis-text-muted">High Confidence:</span>
          <span className="text-[10px] font-mono font-semibold text-green-400">{highConfidenceAlerts.length}</span>
        </div>
        <div className="w-px h-3 bg-pcis-border/30" />
        {patterns.map(pattern => {
          const count = patternCounts[pattern]
          return count > 0 ? (
            <div key={pattern} className="flex items-center gap-1.5">
              <span className="text-[8px] text-pcis-text-muted uppercase">{pattern.split(' ')[0]}:</span>
              <span className="text-[9px] font-mono font-semibold" style={{ color: PATTERN_META[pattern].hex }}>
                {count}
              </span>
            </div>
          ) : null
        })}
      </div>

      {/* ===== PATTERN FILTER PILLS ===== */}
      <div className="px-4 py-3 border-b border-pcis-border/10 flex gap-2 flex-wrap">
        {patterns.map(pattern => {
          const count = patternCounts[pattern]
          const isSelected = selectedPattern === pattern
          const meta = PATTERN_META[pattern]

          return (
            <button
              key={pattern}
              onClick={() =>
                setSelectedPattern(selectedPattern === pattern ? null : pattern)
              }
              className={`text-[9px] px-2.5 py-1 rounded transition-all ${
                isSelected
                  ? `${meta.bgColor} ${meta.borderColor} border`
                  : `border border-pcis-border/20 bg-white/[0.01] hover:bg-white/[0.02]`
              }`}
              style={isSelected ? { color: meta.color.split('-')[1] ? undefined : meta.color } : {}}
            >
              {pattern} ({count})
            </button>
          )
        })}
      </div>

      {/* ===== SCROLLABLE CONTENT ===== */}
      <div className="flex-1 overflow-y-auto space-y-3 p-4">
        {/* HIGH-CONFIDENCE ALERTS (>= 80) */}
        {highConfidenceAlerts.length > 0 && (
          <Panel>
            <PanelHeader title="High-Confidence Alerts" accent="#f59e0b" right={
              <span className="text-[9px] text-pcis-text-muted font-mono">{highConfidenceAlerts.length}</span>
            } />
            <div className="divide-y divide-pcis-border/10 p-3 space-y-2">
              {highConfidenceAlerts.map((pred, i) => {
                const meta = PATTERN_META[pred.pattern]

                return (
                  <div
                    key={i}
                    className="flex items-start gap-3 pt-2 first:pt-0 cursor-pointer hover:bg-pcis-gold/[0.04] rounded-lg px-2 py-2 -mx-2 transition-colors group"
                    onClick={() => setExpandedPrediction(pred)}
                  >
                    <ConfidenceRing confidence={pred.confidence} />
                    <div className="flex-1 min-w-0">
                      <div className="flex items-center gap-2 mb-1">
                        <ClientLink clientId={pred.clientId} className="text-[10px] font-semibold text-white">
                          {pred.clientName}
                        </ClientLink>
                        <span className={`text-[8px] px-2 py-0.5 rounded border ${meta.borderColor} ${meta.color}`}>
                          {pred.pattern}
                        </span>
                      </div>
                      <p className="text-[9px] text-pcis-text-secondary">
                        {pred.description}
                      </p>
                      <span className="text-[8px] text-pcis-gold/0 group-hover:text-pcis-gold/60 transition-colors mt-1 inline-block">
                        VIEW ANALYSIS
                      </span>
                    </div>
                  </div>
                )
              })}
            </div>
          </Panel>
        )}

        {/* ALL PREDICTIONS LIST */}
        {filteredAndSorted.length > 0 ? (
          <Panel>
            <PanelHeader
              title={selectedPattern ? `${selectedPattern}` : 'All Predictions'}
              accent="#d4a574"
              right={
                <span className="text-[9px] text-pcis-text-muted font-mono">{filteredAndSorted.length}</span>
              }
            />
            <div className="divide-y divide-pcis-border/10 p-3">
              {filteredAndSorted.map((pred, i) => {
                const meta = PATTERN_META[pred.pattern]
                const momentum = getMomentumDisplay(pred.momentum)

                return (
                  <div
                    key={i}
                    className="py-2 first:pt-0 last:pb-0 hover:bg-pcis-gold/[0.04] transition-colors cursor-pointer rounded-lg px-2 -mx-2 group"
                    onClick={() => setExpandedPrediction(pred)}
                  >
                    <div className="flex items-start gap-3">
                      <ConfidenceRing confidence={pred.confidence} />
                      <div className="flex-1 min-w-0">
                        <div className="flex items-center gap-2 mb-1">
                          <ClientLink clientId={pred.clientId} className="text-[10px] font-semibold text-white">
                            {pred.clientName}
                          </ClientLink>
                          <span className={`text-[8px] px-2 py-0.5 rounded border ${meta.borderColor} ${meta.color}`}>
                            {pred.pattern}
                          </span>
                        </div>
                        <p className="text-[9px] text-pcis-text-secondary mb-1">
                          {pred.description}
                        </p>
                        <span className="text-[8px] text-pcis-gold/0 group-hover:text-pcis-gold/60 transition-colors inline-block">
                          VIEW ANALYSIS
                        </span>
                      </div>
                      <div className="flex items-center gap-2 flex-shrink-0 ml-2">
                        <span className={`text-[11px] ${momentum.color}`}>
                          {momentum.symbol}
                        </span>
                        <span className="text-[8px] text-pcis-text-muted font-mono">
                          {pred.detectedAt}
                        </span>
                      </div>
                    </div>
                  </div>
                )
              })}
            </div>
          </Panel>
        ) : (
          <Panel>
            <div className="px-4 py-4 text-center">
              <p className="text-[10px] text-pcis-text-muted">
                {selectedPattern
                  ? `No predictions matching "${selectedPattern}"`
                  : 'No predictions available'}
              </p>
            </div>
          </Panel>
        )}

        {/* ===== PCISCOM INTEGRATION NOTE ===== */}
        <div className="text-[8px] text-pcis-text-muted italic px-4 pb-2">
          <span className="text-pcis-gold">&#9670;</span> PCISCOM will auto-feed WhatsApp conversation patterns into prediction signals
        </div>
      </div>
    </div>
  )
}
